### ISSUE TITLE
Feature request: Add single image record

### ISSUE THREAD

**Issue by thhart** [phw/peek#445] opened 2019-05-22 09:13 UTC
It would be nice to have the possibility to simply make one snapshot (frame). The interface is pretty cool and simplified so it could replace any screenshot utility.

**Comment by shinyogre** [comment] 2019-06-04 16:36
In my opinion, this is the only feature that Peek is missing.  Such a feature would be wonderful!

**Comment by phw** [comment] 2019-06-16 09:37
Duplicate of #292, also a wontfix, see comment on #292

**Closed by phw** 2019-06-16 09:37 UTC
Labels: duplicate, wontfix
