### ISSUE TITLE
Consider changing the icon

### ISSUE THREAD

**Issue by ts-web** [phw/peek#382] opened 2018-10-22 17:25 UTC
![image](https://user-images.githubusercontent.com/1311744/47306996-e036de80-d5fb-11e8-80b4-4a5ba1a1f777.png)

I don't know a better way to say this, but the icon bears a strong resemblance to the PornHub logo. The orange color, the white sans-serif capital P -- it's not exactly the same, but it's too similar for my comfort.

Peek is great and everyone should use it, but not everyone knows about Peek. My coworkers walking by my desk might take notice of the icon and wonder, "what's that orange P icon?" And if they don't know about Peek but they are familiar with PornHub, then they'll think I have some sort of porn app installed on my work computer. I love using Peek, but I hate the risk of it being mistaken for PornHub.

This isn't any sort of demand, and it's sad this issue even exists. But this is the way the world is. I'm just humbly asking you to consider distancing Peek from resembling the PornHub brand. It's not Peek's fault, and Peek doesn't need to budge, but I hope you'll consider it.

**Comment by phw** [comment] 2018-10-22 17:38
> I don't know a better way to say this, but the icon bears a strong resemblance to the PornHub logo.

Now you said this I can't unthink it :(

No, seriously, replacing the icon would be most welcomed by me anyway. I just personally lack the design talent to fix this, so I need somebodies help with it. See also https://github.com/phw/peek/issues/114

**Comment by ts-web** [comment] 2018-10-22 17:56
I'll draw up some ideas this evening if I can make some time. Thanks :+1:

**Comment by smaragdus** [comment] 2018-11-01 07:51
This is perhaps the dullest post I have ever read on GitHub. I do not think that porn maniacs should determine program icons. I checked the above mentioned site and its logo is very different- it is square, it has different colour, it uses 'PH' letters for its logo, so I find absolutely no similarities. What others might have think is not a real argument at all. When one wants to find similarities they find it.

**Comment by phw** [comment] 2018-11-01 09:19
@smaragdus Agreed that I also don't see the similarities. But since I would like to change the icon anyway it would be "fixed". Also if some people get this association I'm not here to judge that.

Closing as a duplicate of #114

**Closed by phw** 2018-11-01 09:19 UTC
