### ISSUE TITLE
Error recording at 30fps

### ISSUE THREAD

**Issue by DylanC** [phw/peek#289] opened 2018-03-09 08:56 UTC
Ubuntu 17.10 64bit
Gnome 3
Using X server (not wayland)

Peek: 1.2.2
GTK: 3.22.25
GLib: 2.54.1

Details:
```
GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```

**Comment by DylanC** [comment] 2018-03-12 12:43
Recording at 15fps seemed to work but 30 did not.

**Comment by phw** [comment] 2018-03-16 15:49
I cannot reproduce, but this seems to be an issue with the gnome shell screen recorder. As a workaround you could use the ffmpeg backend by starting peek with `peek -b ffmpeg`

**Comment by DylanC** [comment] 2018-03-19 12:22
@phw - This worked. Thanks!

**Comment by phw** [comment] 2018-03-19 12:59
Ok. I'm gonna close this, as I have no influence in this case. If this bothers you you should file a bug against gnome-shell. But given that it works on my Gnome 3.26 it could well be this has already been fixed upstream.

**Closed by phw** 2018-03-19 12:59 UTC
Labels: bug, upstream

**Comment by DylanC** [comment] 2018-03-19 14:30
@phw - Understandable of course. I have Gnome v3.26.2. Hopefully its fixed in a newer release.
