### ISSUE TITLE
Peek unable to click through on Ubuntu 18.04 and AwesomeWM 4.2 when compton is running

### ISSUE THREAD

**Issue by nanangarsyad** [phw/peek#306] opened 2018-04-06 00:51 UTC
I just found weird behaviour of peek.
When compton is running, I couldn't do any pass through click and also all screen is dark except the mouse.
But if I kill compton, it work as expected.

Here's the detail.
My Compton startup command:
`compton -C -b -c --backend glx --vsync opengl-swc`
The result when compton is running
![peek 2018-04-06 07-41](https://user-images.githubusercontent.com/7588442/38398639-35191906-396f-11e8-8241-cf165849e84e.gif)

**Comment by phw** [comment] 2018-04-10 13:27
That's odd, usually compton was the fix for issues, not the cause. What desktop environment / WM are you running?

**Comment by DougBeney** [comment] 2018-05-07 15:01
@phw I'm having this issue on Fedora 28 w/ GNOME Shell 3.28.1.

**Comment by phw** [comment] 2018-05-07 15:14
@DougBeney You mean you are running compton in Gnome Shell!?

**Comment by nanangarsyad** [comment] 2018-05-16 21:28
Just found out how to fix this issue.
Well it seemed, the running process of compton causing peek to show that behavior (well, I'm not quite sure actually).
So by, disabling/excluding peek in `compton.conf` seemed fix this issue, well, in my case it fixed. Not sure whether it's applicable for the other.

Here's how I exclude peek from compton render.

```
shadow-exclude = [
    "class_g = 'Peek'"
];

fade-exclude = [
    "class_g = 'Peek'"
];

focus-exclude = [
    "class_g = 'Peek'"
];

opacity-rule = [
    "99:class_g = 'Peek'"
];

```

Bellow is sample of peek when compton is running in background/daemon mode.
![mycli-scim](https://user-images.githubusercontent.com/7588442/40145020-8ec10834-598a-11e8-9bf9-abcda47bac69.gif)

**Comment by phw** [comment] 2018-06-05 10:18
I am closing this as whatever this is it is basically a window manager thing. Regarding awesome and clickthrough my last information was that it does not support input shapes at all, so in theory the click through should not work with and without compton running. There is a workaround described in #52 with floating windows and putting Peek behind the thing you want to record.

**Closed by phw** 2018-06-05 10:18 UTC
Labels: wontfix
