### ISSUE TITLE
Can't save files after screen recorded

### ISSUE THREAD

**Issue by troyane** [phw/peek#170] opened 2017-08-04 14:20 UTC
I can record small gifs up to 1-5 seconds, but if I'm going to record bigger gifs each time I get next error:

```
frame=   45 fps= 11 q=-0.0 Lsize=   42225kB time=00:00:04.50 bitrate=76867.4kbits/s speed= 1.1x    
video:42225kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
ffmpeg version 3.2.4-1build2 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (Ubuntu 6.3.0-8ubuntu1) 20170221
  configuration: --prefix=/usr --extra-version=1build2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, x11grab, from ':0+2432,166':
  Duration: N/A, start: 1501856083.528160, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 478x670, 10 fps, 10 tbr, 1000k tbn, 1000k tbc
Output #0, rawvideo, to '/home/tro/.cache/peek/peekC7MB4Y.pam':
  Metadata:
    encoder         : Lavf57.56.101
    Stream #0:0: Video: pam, rgb24, 478x670, q=2-31, 200 kb/s, 10 fps, 10 tbn, 10 tbc
    Metadata:
      encoder         : Lavc57.64.101 pam
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> pam (native))
Press [q] to stop, [?] for help
frame=  382 fps= 10 q=-0.0 Lsize=  358439kB time=00:00:38.20 bitrate=76867.4kbits/s speed=1.01x    
video:358439kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
convert-im6.q16: unable to get registry ID `cache:hosts' @ error/registry.c/GetImageRegistry/201.
convert-im6.q16: DistributedPixelCache '127.0.0.1' @ error/distribute-cache.c/ConnectPixelCacheServer/244.
convert-im6.q16: cache resources exhausted `/home/tro/.cache/peek/peekC7MB4Y.pam' @ error/cache.c/OpenPixelCache/3945.
Error: Child process exited with code 1
File save error: Error when getting information for file “/home/tro/.cache/peek/peekZSHU4Y.gif”: No such file or directory
Temp file delete error: Error removing file /home/tro/.cache/peek/peekZSHU4Y.gif: No such file or directory
```

**Comment by Krandelbord** [comment] 2017-08-16 16:37
I have the same error in peek 1.0.3

```
frame=  290 fps= 10 q=0.0 Lsize=  304654kB time=00:00:29.00 bitrate=86059.4kbits/s dup=12 drop=10    
video:304654kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
convert: unable to get registry ID `cache:hosts' @ error/registry.c/GetImageRegistry/201.
convert: DistributedPixelCache '127.0.0.1' @ error/distribute-cache.c/ConnectPixelCacheServer/244.
convert: cache resources exhausted `/home/emil/.cache/peek/peekL7FI5Y.pam' @ error/cache.c/OpenPixelCache/3943.
Error: Child process exited with code 1
File save error: Error when getting information for file '/home/emil/.cache/peek/peekV4N34Y.gif': No such file or directory
Temp file delete error: Error removing file /home/emil/.cache/peek/peekV4N34Y.gif: No such file or directory

```

**Comment by phw** [comment] 2017-08-20 20:36
Duplicate of #112

The comments there also explain how to increase ImageMagicks resource limits by editing `/etc/ImageMagick-6/policy.xml`

**Closed by phw** 2017-08-20 20:36 UTC
