### ISSUE TITLE
Records one frame too early, countdown still visible.

### ISSUE THREAD

**Issue by D4N13L1980** [phw/peek#569] opened 2020-04-07 15:48 UTC
This is the first frame of a gif created with Peek 1.5.1 from ppa on Ubuntu 18.04.04.

![first_frame](https://user-images.githubusercontent.com/5764662/78689323-806aeb00-78f6-11ea-9831-6e3b31cb8cc1.jpg)

**Comment by phw** [comment] 2020-05-11 22:22
Duplicate of #208 

Unfortunately harder to fix then one might expect. Does not happen always / on all systems.

**Closed by phw** 2020-05-11 22:22 UTC
Labels: duplicate
