### ISSUE TITLE
Binding '<Ctrl><Alt>R` failed after successful build

### ISSUE THREAD

**Issue by rwarren** [phw/peek#283] opened 2018-02-21 02:04 UTC
I just successfully built `peek` on Debian 9 with KDE desktop. After `make` completes successfully, an attempt to run the local `peek` results in a warning and some errors, as below (with the tail end of the make shown as well):
```
 76%] Building C object CMakeFiles/peek.dir/src/ui/about-dialog.c.o
[ 79%] Building C object CMakeFiles/peek.dir/src/ui/application-window.c.o
[ 82%] Building C object CMakeFiles/peek.dir/src/ui/error-dialog.c.o
[ 84%] Building C object CMakeFiles/peek.dir/src/ui/preferences-dialog.c.o
[ 87%] Building C object CMakeFiles/peek.dir/src/ui/shortcut-label.c.o
[ 89%] Building C object CMakeFiles/peek.dir/ui/peek.gresource.c.o
[ 92%] Linking C executable peek
[ 92%] Built target peek
Scanning dependencies of target build-desktop-file
[ 94%] Generating com.uploadedlobster.peek.desktop
[ 94%] Built target build-desktop-file
Scanning dependencies of target build-appdata-file
[ 97%] Generating com.uploadedlobster.peek.appdata.xml
[ 97%] Built target build-appdata-file
Scanning dependencies of target build-manpage
[100%] Generating peek.1.gz
gawk: warning: escape sequence `\ ' treated as plain ` '
[100%] Built target build-manpage
(edms) 0russ@genlee:~/code/github/peek/build$ ls
application.h  application_internal.h  CMakeCache.txt  CMakeFiles  cmake_install.cmake  cmake_uninstall.cmake  CPackConfig.cmake  CPackSourceConfig.cmake  CTestTestfile.cmake  DartConfiguration.tcl  data  Makefile  peek  po  src  Testing  tests  ui
$ ./peek 

** (peek:27402): WARNING **: Binding '<Ctrl><Alt>R' failed!
Error: Child process exited with code 1
Error: Child process exited with code 1
Unable to create default screen recorder.
$
```

The relevant (I think) tail end of an strace is below:

```
recvmsg(7, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(7, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=7, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=7, revents=POLLOUT}])
writev(7, [{iov_base="!\0\4\0%\2\0\0\f\0\33\1\1\0\0\0!\0\4\0%\2\0\0\34\0\33\1\1\0\0\0"..., iov_len=68}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 68
poll([{fd=7, events=POLLIN}], 1, -1)    = 1 ([{fd=7, revents=POLLIN}])
recvmsg(7, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\0\n\224\0%\2\0\0\0\0!\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 160
recvmsg(7, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=7, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=7, revents=POLLOUT}])
writev(7, [{iov_base="\"\33\3\0%\2\0\0\f\0\33\1\"\33\3\0%\2\0\0\34\0\0\0\"\33\3\0%\2\0\0"..., iov_len=52}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 52
poll([{fd=7, events=POLLIN}], 1, -1)    = 1 ([{fd=7, revents=POLLIN}])
recvmsg(7, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\1\235\0\0\0\0\0\6\0\340\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(7, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(7, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
getpeername(2, 0x7ffd8439d340, [128])   = -1 ENOTSOCK (Socket operation on non-socket)
futex(0x7f13ec4f54a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
getpid()                                = 28274
write(2, "\n** (peek:28274): \33[1;33mWARNING"..., 72
** (peek:28274): WARNING **: Binding '<Ctrl><Alt>R' failed!
) = 72
futex(0x7f13ec4f54a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
stat(".", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/russ/code/github/peek/build", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
pipe2([12, 13], 0)                      = 0
pipe2([14, 15], 0)                      = 0
pipe2([16, 17], O_CLOEXEC)              = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f13ee604d50) = 28278
close(13)                               = 0
close(15)                               = 0
close(17)                               = 0
read(12, "", 8)                         = 0
close(12)                               = 0
select(17, [14 16], NULL, NULL, NULL)   = 2 (in [14 16])
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=28278, si_uid=1000, si_status=1, si_utime=0, si_stime=0} ---
read(14, "", 4096)                      = 0
close(14)                               = 0
read(16, "", 4096)                      = 0
close(16)                               = 0
wait4(28278, [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 28278
write(2, "Error: Child process exited with"..., 40Error: Child process exited with code 1
) = 40
pipe2([12, 13], 0)                      = 0
pipe2([14, 15], 0)                      = 0
pipe2([16, 17], O_CLOEXEC)              = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f13ee604d50) = 28279
close(13)                               = 0
close(15)                               = 0
close(17)                               = 0
read(12, "", 8)                         = 0
close(12)                               = 0
select(17, [14 16], NULL, NULL, NULL)   = 2 (in [14 16])
read(14, "", 4096)                      = 0
close(14)                               = 0
read(16, "", 4096)                      = 0
close(16)                               = 0
wait4(28279, [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 28279
write(2, "Error: Child process exited with"..., 40Error: Child process exited with code 1
) = 40
write(2, "Unable to create default screen "..., 42Unable to create default screen recorder.
) = 42
write(6, "\1\0\0\0\0\0\0\0", 8)         = 8
futex(0x560a60674de0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560a60676ee0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560a607194e0, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
write(6, "\1\0\0\0\0\0\0\0", 8)         = 8
futex(0x560a60674de0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560a60676ee0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x560a6066b058, FUTEX_WAKE_PRIVATE, 1) = 1
poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}], 3, 0) = 1 ([{fd=8, revents=POLLIN}])
recvmsg(7, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(8, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\0\0010\0\0\0\240*\0\0\216\0\0\0\1\1o\0\37\0\0\0/org/a11"..., iov_len=2048}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_CMSG_CLOEXEC) = 328
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
recvmsg(8, {msg_namelen=0}, MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(7, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}], 3, 0) = 1 ([{fd=3, revents=POLLIN}])
read(3, "\2\0\0\0\0\0\0\0", 16)         = 8
sendmsg(8, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\2\1\1\0\0\0\0\6\0\0\0\30\0\0\0\6\1s\0\5\0\0\0:1.16\0\0\0"..., iov_len=40}, {iov_base="", iov_len=0}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 40
recvmsg(7, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}], 3, 0) = 0 (Timeout)
sendmsg(8, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\0\1\0\0\0\0\7\0\0\0\204\0\0\0\1\1o\0\30\0\0\0/org/a11"..., iov_len=152}, {iov_base="", iov_len=0}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 152
sendmsg(8, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\0\1\0\0\0\0\10\0\0\0\246\0\0\0\1\1o\0.\0\0\0/org/a11"..., iov_len=184}, {iov_base="", iov_len=0}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 184
sendmsg(8, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\0\1\0\0\0\0\t\0\0\0\250\0\0\0\1\1o\0.\0\0\0/org/a11"..., iov_len=184}, {iov_base="", iov_len=0}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 184
recvmsg(7, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}], 3, 0) = 1 ([{fd=8, revents=POLLIN}])
recvmsg(8, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\2\1\1\10\0\0\0\242*\0\0006\0\0\0\6\1s\0\6\0\0\0:1.107\0\0"..., iov_len=2048}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_CMSG_CLOEXEC) = 256
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
recvmsg(8, {msg_namelen=0}, MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(7, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}], 3, 0) = 1 ([{fd=3, revents=POLLIN}])
read(3, "\3\0\0\0\0\0\0\0", 16)         = 8
recvmsg(7, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}], 3, 0) = 0 (Timeout)
recvmsg(7, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}], 3, 0) = 0 (Timeout)
recvmsg(7, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}], 3, 0) = 0 (Timeout)
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by gort818** [comment] 2018-02-23 02:51
Cannot reproduce this, you do have libkeybinder3 correct?

**Comment by phw** [comment] 2018-02-23 12:41
There are two things here:

1. The `Binding '<Ctrl><Alt>R' failed!` warning: This is unrelated to Peek not starting, usually it just means that the given shortcut is already in use. In Peek itself you can change the shortcut to anything you want, this should solve this issue.

2. Peek not starting due to "Unable to create default screen recorder.": On KDE Peek uses ffmpeg to record the screen, please install ffmpeg and try starting Peek again.

**Comment by phw** [comment] 2018-03-20 07:28
@rwarren I will close this as I highly suspect ffmpeg was missing for you. If this was not the issue, please let me know.

**Closed by phw** 2018-03-20 07:28 UTC
Labels: question

**Comment by shollingsworth** [comment] 2018-07-17 21:12
I'm seeing this same issue, did an strace and these are the top hits
`peek` starts, but I can't bring the window to the foreground (Using KDE)
```
     94 28550 recvmsg(7, 0x7ffc2d519140, 0)     = -1 EAGAIN (Resource temporarily unavailable)
    101 28550 close(13)                         = 0
    163 28550 poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}], 3, 500) = 1 ([{fd=7, revents=POLLIN}])
    216 28550 recvmsg(7, 0x7ffc2d519640, 0)     = -1 EAGAIN (Resource temporarily unavailable)
    220 28550 recvmsg(7, 0x7ffc2d519790, 0)     = -1 EAGAIN (Resource temporarily unavailable)
    238 28550 close(12)                         = 0
    350 28550 poll([{fd=7, events=POLLIN}], 1, -1) = 1 ([{fd=7, revents=POLLIN}])
    383 28550 poll([{fd=7, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=7, revents=POLLOUT}])
    396 28550 futex(0x7fd3f87e5428, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    454 28550 recvmsg(7, 0x7ffc2d519770, 0)     = -1 EAGAIN (Resource temporarily unavailable)
    644 28550 poll([{fd=3, events=POLLIN}, {fd=7, events=POLLIN}, {fd=8, events=POLLIN}], 3, 0) = 0 (Timeout)
```
