### ISSUE TITLE
Recordings can't be saved if Peek is maximised and Gnome dash is opened

### ISSUE THREAD

**Issue by Alexander-Wilms** [phw/peek#157] opened 2017-06-20 01:01 UTC
I'm using the Flatpak version. While I can store screen recordings of the dash if Peek isn't in fullscreen mode, it doesn't work when I maximise the Peek window. If the dash isn't being opened during the recording, the recording can be saved regardless of the maximised/unmaximised state of Peek.

**Comment by phw** [comment] 2017-06-20 09:59
I actually suspect this has more to do with the size of the recording view than the dash. Are you recording as GIF?

Can you please run peek from command line and make a recording that fails, than post the console output here. Also make sure to use latest Peek 1.0.3, as this actually fixes a quality issue with gnome-shell recording that also affected file size and therefor postprocessing times negatively.

**Comment by Alexander-Wilms** [comment] 2017-06-20 15:38
Yes, I'm recording as GIF. And I noticed that the issue also occurs if the Peek window is only almost maximised, so you're probably right.

I'll post the console output later today.

**Comment by e-cloud** [comment] 2017-06-23 08:12
same problem here. The most important save feature is offline now and then. And there is not dash opened.

**Comment by e-cloud** [comment] 2017-06-23 08:18
![image](https://user-images.githubusercontent.com/5255354/27472831-8289aeac-582f-11e7-8949-cc5b8820f53c.png)

**Comment by phw** [comment] 2017-06-23 08:20
@e-loud, are you also using the Flatpak version? Then this would actually be very strange.Your error is that convert runs into configured resource limits, see https://github.com/phw/peek/issues/112 for discussion and workarounds.

@Alexander-Wilms Can you give your console output?

**Comment by e-cloud** [comment] 2017-06-23 08:28
No, I install it from ppa

**Comment by e-cloud** [comment] 2017-06-23 09:00
@phw thx, solve it with upgrading the config of imagemaigck

**Comment by Alexander-Wilms** [comment] 2017-06-23 12:36
I ran it today, and the only issue seems to be that it takes very long to render the gif. Maybe I previously closed peek too early.

Output:
```
** (peek:2): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-lhrHYuSfgA: Connection refused
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Using screen recorder backend gnome-shell
Recording to file /home/awilms/.var/app/com.uploadedlobster.peek/cache/peek/peekV14S1Y.avi
```

**Comment by phw** [comment] 2017-07-05 12:13
Closing this as duplicate of #112

**Closed by phw** 2017-07-05 12:13 UTC
Labels: bug, need-more-info
