### ISSUE TITLE
Recording stops when window is moved

### ISSUE THREAD

**Issue by abhilash1in** [phw/peek#171] opened 2017-08-04 17:21 UTC
Would be a nice feature if I am able to change the area being recorded on the fly. Currently, recording stops as soon as I try to move the recording frame

**Comment by phw** [comment] 2017-08-20 20:31
Duplicate of #27

But I actually think that #27 is a wontfix, as I don't see a way to handle this. The app does not get notified synchronously on window moves, so all attempts to do this would likely record the window borders.

**Closed by phw** 2017-08-20 20:31 UTC
Labels: duplicate
