### ISSUE TITLE
Peek Window is really thin, making it very hard to resize

### ISSUE THREAD

**Issue by davidv171** [phw/peek#199] opened 2017-10-23 11:42 UTC
I'm not sure fi this is a good question for Github, but I've noticed the Window is very very thin, making it a pain in the ass to try to resize, the thingie is also completely transparent. 

https://i.imgur.com/GoITz3b.png

How do I fix this? This wasnt the issue when I installed Peek on my last Ubuntu install.

**Comment by phw** [comment] 2017-10-23 12:16
Is this the default Ubuntu theme? Which version of Ubuntu is this on? Maybe I have to tweak the styling for this particular theme a bit.

**Comment by davidv171** [comment] 2017-10-23 12:36
Changed to defualt theme. Gnome. https://i.imgur.com/PmEZR1r.png

This is how it looks like with. Still way too thin but at least it's not transparent anymore.

**Comment by phw** [comment] 2017-10-23 12:39
Actually it is so thin by purpose, but with the Adwaita theme or Arc (which I use) it is not a big deal, since the area to grab for resizing is larger then just the thin border (you can grab slightly outside the border).

I have to test, maybe you could even click slightly inside the border, but this is prevented by the click through of Peek. If so I might make the click-through area 2 or 3 pixel smaller to allow for easier resizing.

**Comment by davidv171** [comment] 2017-10-23 12:40
Okay. Thank you for your time.

**Comment by cGuille** [comment] 2017-10-25 08:19
Hello!

I just installed Peek and encountered the same issue on KDE (Plasma 5.5.5).
It is nearly impossible to resize the window.

Besides that, Peek seems really nice! Thank you.

Please tell me if I can help you or if you need more details about the issue.

**Comment by phw** [comment] 2017-10-25 11:06
> Please tell me if I can help you or if you need more details about the issue.

I will take a look. What GTK theme is this then?

**Comment by cGuille** [comment] 2017-10-25 12:34
> What GTK theme is this then?

I am not famliar with desktop themes so I am not sure I use a GTK theme since I run KDE.

The KDE theme is Breeze (I suppose it corresponds to [this project](https://github.com/KDE/breeze)), this is one of the official (pre-installed) themes as far as I know.
In the KDE settings there is an option to choose GTK themes, maybe this is what is used for GTK applications? If that is so, The GTK theme is also Breeze, presumably [this](https://github.com/KDE/breeze-gtk).

Does this answer your question?

For your information, here is how Peek looks on my machine:
![screenshot576](https://user-images.githubusercontent.com/803869/31998634-cfdb0418-b990-11e7-9e76-fe0b11135d9d.png)

**Comment by pcj** [comment] 2017-11-02 00:02
I can confirm this in ubuntu 16.04 with gnome desktop. Basically impossible to resize, but double-clicking the title bar does maximize it.

**Comment by phw** [comment] 2017-11-07 23:14
I cannot really reproduce this. This is how Peek looks with the default Ubuntu Ambiance theme on Ubuntu 17.10 GNOME:

![bildschirmfoto vom 2017-11-08 00-05-10](https://user-images.githubusercontent.com/29852/32522684-947b269a-c418-11e7-96f1-0d0832118791.png)

You can drag the border easily, as the entire shadow area around the window is draggable.

Same on 16.04 Unity:

![bildschirmfoto vom 2017-11-08 00-10-59](https://user-images.githubusercontent.com/29852/32522939-85863f52-c419-11e7-870c-16d2e3c9f211.png)

Haven't tested that KDE theme yet.

**Comment by phw** [comment] 2017-11-07 23:31
Now I also tried the Breeze theme. It maybe looks thinner, but behaves exactly the same. Just to make this clear: In the screenshots above I have easily an area of 10-14 pixels around the edge where I can drag. Isn't that the case for you?

Also I can make the visible border around the inner recording area thicker, but that has no influence on the area that is available for resizing. Peek just provides as much space for resizing as every other window I tried to open.

**Comment by phw** [comment] 2017-11-07 23:32
@davidv171 The only screenshot here that looks of is https://i.imgur.com/GoITz3b.png from your original report. This is also Ambiance, right? What desktop environment is it?

**Comment by davidv171** [comment] 2017-11-07 23:40
@phw yes it was ambiance.

**Comment by davidv171** [comment] 2017-11-07 23:41
Since I cant edit on mobile its gnome(think I mentioned that somewhere)

**Comment by pcj** [comment] 2017-11-07 23:42
Can I use peek to record peek itself?  (Probably not)

**Comment by cGuille** [comment] 2017-11-08 08:46
Hello @phw,

Thank you for considering the issue.

> Now I also tried the Breeze theme. It maybe looks thinner, but behaves exactly the same. Just to make this clear: In the screenshots above I have easily an area of 10-14 pixels around the edge where I can drag. Isn't that the case for you?

No, not for me.

It seems that:
- I can resize the window using the top of the window, as there is the title bar.
- I can resize the window using the left border if I am **really** careful (I suppose it is a 1px hitbox).
- I can not resize the window at all using the bottom nor the right border of the window.

> Also I can make the visible border around the inner recording area thicker, but that has no influence on the area that is available for resizing. Peek just provides as much space for resizing as every other window I tried to open.

This is not the case on KDE : the issue I described does not apply to windows of other applications such as Firefox, Konsole, KeePassXC…

**Comment by phw** [comment] 2017-11-17 20:24
Just an update: In order to reproduce this I tried installing KDE Plasma in my Ubuntu 16.04 VM. Unfortunately Plasma is completely unusable and broken there (most windows are undecorated and full of graphical glitches) and I can't really test with this. Maybe I should install a newer Kubuntu instead or run on real hardware via live CD.

**Comment by pcj** [comment] 2017-11-17 21:49
@phw If you want a decent dedicated linux laptop, the Dell XPS 13 with ubuntu 16.04 preinstalled is pretty good.  Something like $1500 cheaper than a Mac too.

**Comment by cGuille** [comment] 2017-11-18 09:29
I cloned the repo and tried to tweak some properties in the `application-window.ui` file without success. I tried to set a border width; it displayed a border but it was not related to the ability to grab the window for resize.

Then I made a bit of research on the subject and found nothing. It was difficult since I do not know anything about GTK or desktop application UI in general, so maybe I did not search with proper keywords.

In the end I found a workaround using the KDE settings: I configured a KWin keyboard shortcut to resize the current window. I still can not grab the window's edges to resize it, but I can trigger a resize using a custom keyboard shortcut.

**Comment by cGuille** [comment] 2017-11-18 09:35
I made a screen capture of Peek (using Peek :smile: ) to demonstrate the following statement:

> It seems that:
> - I can resize the window using the top of the window, as there is the title bar.
> - I can resize the window using the left border if I am **really** careful (I suppose it is a 1px hitbox).
> - I can not resize the window at all using the bottom nor the right border of the window.

![peek 18-11-2017 10-31](https://user-images.githubusercontent.com/803869/32978942-1c9577ac-cc4c-11e7-8bb8-4b14020fd012.gif)

**Comment by phw** [comment] 2017-11-18 21:01
I installed KDE Neon in a VM to test this, and yes, I can easily reproduce it. Unfortunately this seems to be an issue with KWin having issues with GTK3 client side decorations (CSD). For some reason the drop shadow is not rendered (which in case of CSD windows GTK3 would need to do). I don't know whether this is a defect in GTK3 or KWin. I could also reproduce the very same annoying issue with GNOME Todo and GNOME calculator.

There are two workarounds:

1. Change the GTK3 theme

in Settings > Application Style > GNOME Application Style set the GTK3 theme to "default". Now Peek will have a larger draggable border, but GTK applications will look a bit out of place and less integrated.

2. Set theme and window manager overrides for Peek
Basically do what is described in https://www.reddit.com/r/kde/comments/563snw/no_shadows_around_some_windows_in_kde_57/ for Peek.

In [ System settings ] -> [ Window management ] -> [ Window rules ] -> [ Appearance & Fixes ] , set [ No titlebar and frame] to No  
In [ System settings ] -> [ Application Style ] -> [ Window decoration ] -> [ Breeze theme setting ] -> [ Window specific overrides ], Set [ border size ] to Normal and set [ Hide Window title bar ] to yes.

The last step differs a bit from the linked description. The border size should be set to Normal or Tiny, but not No border. With No border you would get an ugly resize triangle in the lower right border, which also is visible in recordings. Still this looks a bit odd, as there will be an extra frame around the Peek window, but it makes it usable.

Next step is trying to figure out if I can do anything in the theming to make it work a bit better on KWin with Breeze. After all the default GTK3 theme Adwaita seems to have a workaround for it.

**Comment by phw** [comment] 2017-11-18 21:15
Related discussion and bug: https://bugzilla.gnome.org/show_bug.cgi?id=729721

The status quo is that GTK does not draw the shadow, as it causes issues with KWin. Not sure exactly what the issues are, but presumably it has to do with size calculations, as the shadows are outside the window and should not be taken by the WM as the outer border of the entire window.

**Comment by phw** [comment] 2017-11-19 00:31
I made some changes to the theme to allow for a larger resize border on Plasma if the Breeze theme is used:

![bildschirmfoto vom 2017-11-19 01-27-17](https://user-images.githubusercontent.com/29852/32986061-d12588ca-ccc8-11e7-9a1d-ccdb0c644675.png)

Could you try the latest development release to see if this fixes your issue? Daily PPA builds and Snap package on edge  are currently building and should provide the latest code soon.

**Comment by cGuille** [comment] 2017-11-19 08:30
Hello,

Thank you for trying this!

I built Peek from sources (on `master`).
Unfortunately, this does not seem to do the trick on my setup:
![peek 2017-11-19 09-20](https://user-images.githubusercontent.com/803869/32988803-057b038c-cd0c-11e7-896e-326cee5c4388.gif)

But if the issue is caused by GTK or KWin, maybe you should not change anything in Peek?
As far as I am concerned, I can deal with it thanks to the workaround described earlier in the thread, and we do not even know if this issue concerns a lot of setups.

**Comment by phw** [comment] 2017-11-19 08:38
@cGuille I guess the theme detection is not working as it should. Currently I have to detect whether KDE is running to get th
KDE's theme config. Could you give me the output of `env` on your system. Especially the values of XDG_SESSION_DESKTOP, DESKTOP_SESSION and XDG_CURRENT_DESKTOP.

Basically all KDE users using the default theme are affected. I think given the general disagreement between the KWin and GTK teams regarding CSD it is unlikely we will get a proper solution from upstream, so a workaround sounds like a good idea.

**Comment by cGuille** [comment] 2017-11-19 08:47
Here it is:

```
$ env | grep -E '(XDG_SESSION_DESKTOP|DESKTOP_SESSION|XDG_CURRENT_DESKTOP)'
DESKTOP_SESSION=/usr/share/xsessions/plasma
XDG_SESSION_DESKTOP=KDE
XDG_CURRENT_DESKTOP=KDE
```

**Comment by phw** [comment] 2017-11-19 08:59
@cGuille Ok, that should work. What is the contents of `$HOME/.config/gtk-3.0/settings.ini`? Can you also start Peek (latest source again) with

    G_MESSAGES_DEBUG=all peek

That should output the detected GTK theme.

**Comment by cGuille** [comment] 2017-11-19 09:13
```
$ cat $HOME/.config/gtk-3.0/settings.ini
[Settings]
gtk-font-name=Noto Sans Regular 10
gtk-theme-name=Breeze
gtk-icon-theme-name=breeze
gtk-fallback-icon-theme=Humanity
gtk-toolbar-style=GTK_TOOLBAR_ICONS
gtk-menu-images=1
gtk-button-images=1
```

```
$ G_MESSAGES_DEBUG=all ./peek 
(peek:8255): Gtk-DEBUG: Connecting to session manager
** (peek:8255): DEBUG: desktop-integration.vala:168: Desktop: KDE
** (peek:8255): DEBUG: application.vala:286: GTK theme: Breeze
** (peek:8255): DEBUG: desktop-integration.vala:168: Desktop: KDE
** (peek:8255): DEBUG: application.vala:341: Decoration layout: menu:minimize,maximize,close
** (peek:8255): DEBUG: desktop-integration.vala:168: Desktop: KDE
** (peek:8255): DEBUG: desktop-integration.vala:168: Desktop: KDE
** (peek:8255): DEBUG: utils.vala:68: Looking for executable ffmpeg (0): /usr/bin/ffmpeg

Using screen recorder backend ffmpeg
** (peek:8255): DEBUG: application-window.vala:793: Decoration layout: menu:minimize,maximize,close
** (peek:8255): DEBUG: recording-area.vala:38: Absolute recording area x: 410, y: 239, w: 759, h: 431
** (peek:8255): DEBUG: recording-area.vala:45: Screen w: 1600, h: 900
** (peek:8255): DEBUG: recording-area.vala:58: Clipped recording area x: 410, y: 239, w: 759, h: 431
** (peek:8255): DEBUG: recording-area.vala:69: Scaled recording area x: 410, y: 239, w: 759, h: 431
** (peek:8255): DEBUG: recording-area.vala:38: Absolute recording area x: 410, y: 239, w: 759, h: 431
** (peek:8255): DEBUG: recording-area.vala:45: Screen w: 1600, h: 900
** (peek:8255): DEBUG: recording-area.vala:58: Clipped recording area x: 410, y: 239, w: 759, h: 431
** (peek:8255): DEBUG: recording-area.vala:69: Scaled recording area x: 410, y: 239, w: 759, h: 431
** (peek:8255): DEBUG: application-window.vala:204: delete_event: recorder.is_recording=false, window.is_postprocessing=false
** (peek:8255): DEBUG: application.vala:116: Application got shutdown signal
```

**Comment by phw** [comment] 2017-11-19 09:19
That's actually all looking good :( No idea why this is not working. What MADE version on which distribution is this? I only tested on KDE Neon with latest Plasma.

**Comment by cGuille** [comment] 2017-11-19 09:51
What is MADE and how can I find out its version?

I use Kubuntu 16.04 (upgraded from previous versions). 
It runs KDE Plasma 5.5.5 with Qt 5.5.1. 

<img alt="screenshot603" src="https://user-images.githubusercontent.com/803869/32989489-5b94d7e2-cd17-11e7-8af1-53de2a6e1a19.png" width="300" />

**Comment by phw** [comment] 2017-11-19 10:01
> What is MADE and how can I find out its version?

Sorry, I am writing from my mobile and auto correction jumped in, meant KDE. What GTK version is installed?

**Comment by cGuille** [comment] 2017-11-19 10:08
Does this answer the question? I am not sure.

```
$ dpkg -l libgtk2.0-0 libgtk-3-0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                       Version            Architecture       Description
+++-==========================-==================-==================-==========================================================
ii  libgtk-3-0:amd64           3.18.9-1ubuntu3.3  amd64              GTK+ graphical user interface library
ii  libgtk2.0-0:amd64          2.24.30-1ubuntu1.1 amd64              GTK+ graphical user interface library
ii  libgtk2.0-0:i386           2.24.30-1ubuntu1.1 i386               GTK+ graphical user interface library

**Comment by phw** [comment] 2017-11-19 10:11
Yes, thanks a lot for this info. I will try to figure out what's still going wrong :)

**Comment by phw** [comment] 2017-11-20 09:46
@cGuille I tested on Kubuntu 16.04 with Breeze theme, works for me. I tested on the live CD and installed from daily PPA. Could you also test the daily PPA version:

```
sudo add-apt-repository ppa:peek-developers/daily
sudo apt update
sudo apt install peek
```

**Comment by cGuille** [comment] 2017-11-20 11:00
Nothing changed for me. :s

The update did happen from the daily PPA:
```
[…]
Réception de:1 http://ppa.launchpad.net/peek-developers/daily/ubuntu xenial/main amd64 peek amd64 1.1.0-1+git788~ppa17~ubuntu16.04.1 [149 kB]
[…]
```

Here is the installed version:
```
$ dpkg -l peek
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                              Version               Architecture          Description
+++-=================================-=====================-=====================-========================================================================
ii  peek                              1.1.0-1+git788~ppa17~ amd64                 Simple screen recorder with an easy to use interface
```

But the issue remains.

**Comment by phw** [comment] 2017-11-20 14:10
That's the latest version. Have you disabled all the KDE settings overrides that I mentioned above as a workaround?

**Comment by gort818** [comment] 2017-11-20 23:13
I am going to boot up a Kubutu live cd and do some testing with this.

**Comment by cGuille** [comment] 2017-11-21 08:42
> That's the latest version. Have you disabled all the KDE settings overrides that I mentioned above as a workaround?

Oh non, I thought it was either the workaround or the fix. Sorry.

**Comment by phw** [comment] 2017-11-21 09:25
> Oh no, I thought it was either the workaround or the fix. Sorry.

Not sure we understand each other: The fix alone should be enough. The workarounds should not be applied in this case. I don't know what happens if you apply the workarounds, but it could very well interfere with the fix..

**Comment by cGuille** [comment] 2017-11-21 09:55
So we understood each other until you last question, which I misinterpreted.

No, I did not changed the settings as in your workaround.
I prefer using a keyboard shortcut to resize the window rather than affecting my whole desktop environment.

**Comment by gandalf3** [comment] 2017-12-17 09:31
Would it be possible to draw the transparent overlay which shows the window size up until recording starts? That way we could easily resize with a <kbd>Alt</kbd> (or <kbd>Meta</kbd>) + <kbd>Right mouse</kbd> drag. Then the fix doesn't depend on a specific theme/desktop environment.

**Comment by atar-axis** [comment] 2018-02-17 15:41
I have exactly the same problem, using Antergos and latest KDE on Breeze Theme.

![issue_thin_border](https://user-images.githubusercontent.com/11148588/36342630-62365054-1401-11e8-8511-6fd007c2e0b3.gif)

**Comment by phw** [comment] 2018-03-20 19:58
Back at this again. @gandalf3  I like your suggestion, so I have it a quick and dirty try. In the branch https://github.com/phw/peek/tree/easier-window-resizing-on-kde the click-through behavior is disabled while not recording. And then you can easily resize as you said using the mouse (Alt + right click). Currently it is a bit confusing, because the overlay is not shown, so the area is completely transparent. But I will likely clean this up and show the overlay all the time.

Apart from this I am still puzzled why the theme changes are not applied in some cases. For me Peek works very much like any native KDE application regarding the resizing behavior. For me the resizing area at the edges in anooyingly small in all apps, this seems to be a general issue with the Breeze theme.

**Comment by gandalf3** [comment] 2018-03-21 00:50
@phw Excellent, that's so much better! This way it's easier to use on more unusual WMs as well; I'm currently running bspwm which doesn't do edge-resizing at all, making some version of <kbd>Alt</kbd><kbd>RMB</kbd> rather indispensable. That said, even when I was using KDE I pretty much never used the edges to resize, preferring <kbd>Super</kbd><kbd>RMB</kbd>.

**Comment by gort818** [comment] 2019-02-13 00:46
I just tested on plasma 5.15 the newest release and breeze theme finally works! They fixed a lot of gtk theme problems in the latest release.

**Comment by atar-axis** [comment] 2019-02-13 10:26
I can confirm that, latest Plasma finally fixed the issue:

![image](https://user-images.githubusercontent.com/11148588/52705005-2684c480-2f82-11e9-870c-ecb2ef800630.png)

**Comment by gort818** [comment] 2019-06-29 16:33
@phw I think we can close this, seems to work fine now.

**Comment by gandalf3** [comment] 2019-06-29 20:57
Still thin and impossible to resize for me, Peek 1.4.1 on bspwm

**Comment by benjie** [comment] 2019-07-27 17:07
I'm here because it's thin and impossible for me to resize on my KDE Plasma desktop; I think it's because I've set window borders to none (they're thinner than in @atar-axis's image above, literally exactly one pixel wide). Other windows have a resize area that expands around the window a few pixels, but Peek doesn't seem to (perhaps because it's Gtk?)

Thanks for writing/maintaining this awesome utility, other than the lack of resizing my first experience was great!

**Comment by zebzorb** [comment] 2019-09-29 09:03
> In [ System settings ] -> [ Window management ] -> [ Window rules ] -> [ Appearance & Fixes ] , set [ No titlebar and frame] to No
>
> In [ System settings ] -> [ Application Style ] -> [ Window decoration ] -> [ Breeze theme setting ] -> [ Window specific overrides ], Set [ border size ] to Normal and set [ Hide Window title bar ] to yes.
>
> The last step differs a bit from the linked description. The border size should be set to Normal or Tiny, but not No border. With No border you would get an ugly resize triangle in the lower right border, which also is visible in recordings. Still this looks a bit odd, as there will be an extra frame around the Peek window, but it makes it usable.

It's an old issue, but I tried this workaround and it works great in Plasma (5.16.5). Setting the border size to "no borders" works fine too -- it doesn't have a resize triangle for me.

![Peek 2019-09-29 03-53](https://user-images.githubusercontent.com/1666748/65829689-86a84c80-e26d-11e9-98be-e23407a6aa3a.gif)

**Comment by eschoeller** [comment] 2019-10-13 17:34
This is still a problem for me even after trying to apply that work-around. I found that holding the alt key and doing a right-click-drag was the easiest way to resize the window. 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
```

**Comment by clofresh** [comment] 2019-10-15 20:40
I'm using Awesome on Arch Linux and also am having trouble resizing. If changing the border size is too difficult I would also be happy with a way directly enter the size of the capture window.

**Comment by gandalf3** [comment] 2019-10-15 23:00
@clofresh have you tried this branch? https://github.com/phw/peek/issues/199#issuecomment-374805943

Perhaps a way to snap to the geometry of existing windows (even as simple as providing a way to specify the window geometry via command line) would be an acceptable workaround?

**Comment by xekon** [comment] 2020-02-22 16:48
If your on KDE hold have the peek window in the foreground (selected)

hold down ALT and use the right mouse button to click and drag corners to resize.

This works well for me.

**Comment by ponchofiesta** [comment] 2020-02-27 07:18
I can't understand why this is related to the theme being used. There should be a border with same thickness on every theme. This should be done by own code, not by depending on the theme or the desktop environment.

**Comment by phw** [comment] 2020-02-27 07:33
@ponchofiesta Because basically Plasma did not fully support GTK windows with client decorations, and for those the border is part of the application. That also means themes affect the border size.

But Plasma 5.18 actually fixes this, fully supporting GTK windows with client decoration, including drop shadow and bigger area around the window to grab for resizing. With this it now actually looks and works like on e.g. GNOME. I am going to close this issue as everything else that can be done here is just dirty workarounds and hacks.

**Closed by phw** 2020-02-27 07:33 UTC
Labels: bug, upstream

**Comment by xekon** [comment] 2020-02-27 07:43
Just wanted to post that I am on latest KDE (Ubuntu 18.04.4 and plasma-desktop) and still have trouble grabbing the bottom left and right corners to resize the peek windows. However if you right click on the title bar of the peek aplication you can choose the resize option. I found this helpful.

**Comment by ponchofiesta** [comment] 2020-02-27 07:54
@phw Don't depend on the window border. Make your own border. I'm not sure how that could be done in GTK. In .NET on Windows I would add some dummy controls of 3px width/height around and add handlers to adjust the cursor on mouse over and resize the window on click+move. Yes, it's still kind of dirty but it should work everywhere. Maybe you could add a parent GtkGrid (3x3) and move the current content to the center cell. Than place those dummy controls around. But I'm not sure if it is possible to set fixed width/height on those controls. But something like this might fix it.

**Comment by phw** [comment] 2020-02-27 08:51
@ponchofiesta Sorry, I'm not interested in reimplementing parts of Gtk and implement custom window handling just because Plasma does not handle this properly. Especially not since they now fixed it.

**Comment by ponchofiesta** [comment] 2020-02-27 10:23
OK, I will continue to use Peek from Snap for now till Kubuntu 20.04.1 is out which hopefully comes with latest Plasma wich fixes it. Please don't remove it :-)

**Comment by chikamichi** [comment] 2021-08-23 18:48
In KDE/Plasma, one may tweak a specific window's config. Here's an example (French UI):

![ksnip(55)](https://user-images.githubusercontent.com/106689/130499511-5f5a7f61-829a-4a63-9855-6a0944ceb1f4.png)
![ksnip(56)](https://user-images.githubusercontent.com/106689/130499518-afb0b5af-91c6-437c-9b46-4d233c79b1bd.png)

0. Launch Peek.
1. Open _System Settings > Window Management > [Window Rules](https://userbase.kde.org/System_Settings/Window_Rules)_. Add a new config entry. The goal here is to define a rule which will automatically apply custom settings to a matching window, based on detection rules.
2. Name it whatever you like (here: _Peek_), and click "Detect Window Properties". Click on Peek's window. Validate the settings to fill-in the config entry. You may enable "Match whole window class" for a more precise matching (likely not to be necessary in this case).
3. In the "Appearance & Fixes" tab…
4. … enable the first rule to force borders onto Peek's window. Warning: this rule is negative, so make sure to enable "No" as a setting to actually force borders to appear.
5. Don't forget to _Apply_ this new rule. Relaunch Peek _and voilà !_
