### ISSUE TITLE
Temp file deleted error

### ISSUE THREAD

**Issue by seanh** [phw/peek#133] opened 2017-04-21 10:13 UTC
I'm using Peek 1.0.1 from the daily builds PPA <https://launchpad.net/~peek-developers/+archive/ubuntu/daily>, I keep finding that after _Rendering..._ no file is saved, and I saw these errors in the terminal:

```
Using screen recorder backend gnome-shell
Recording to file /home/seanh/.cache/peek/peekGHEUYY.mp4
convert-im6.q16: unable to get registry ID `cache:hosts' @ error/registry.c/GetImageRegistry/201.
convert-im6.q16: DistributedPixelCache '127.0.0.1' @ error/distribute-cache.c/ConnectPixelCacheServer/244.
convert-im6.q16: cache resources exhausted `/home/seanh/.cache/peek/magick-15589Z10NOskfB7ok.pam' @ error/cache.c/OpenPixelCache/3945.
Error: Child process exited with code 1
File save error: Error when getting information for file “/home/seanh/.cache/peek/peekSYSPYY.gif”: No such file or directory
Temp file delete error: Error removing file /home/seanh/.cache/peek/peekSYSPYY.gif: No such file or directory
```

I'm using output format GIF

**Comment by seanh** [comment] 2017-04-24 13:55
Stable version seems to have the same issue. Peek is unfortunately completely unusable for me now

**Comment by phw** [comment] 2017-04-24 14:08
But it worked for you previously? Did something change or is this a different system?

The error message indicates that there is not enough disk space for processing, how much space is there in your home? If it crashed in between maybe there are also left over files in /home/seanh/.cache/peek/

**Comment by seanh** [comment] 2017-04-24 14:24
Went back and tried versions 1.0.0 and 0.9.1 (building from source), also tried the flatpak, and each different `--backend`, all have the same problem.

It _did_ work for me before yes, on this same system. I did recently upgrade to Ubuntu Gnome 17.04, maybe that caused it?

Lots of space left in my home (about 40GB).

Leftover cache files:

```
$ ls .cache/peek/
peek7EDJYY.pam  peekIQ80XY.gif  peekMRGJXY.pam  peekYWYLXY.pam
$ du -hs .cache/peek/*
939M    .cache/peek/peek7EDJYY.pam
1.1M    .cache/peek/peekIQ80XY.gif
0       .cache/peek/peekMRGJXY.pam
0       .cache/peek/peekYWYLXY.pam
```

**Comment by seanh** [comment] 2017-04-24 14:26
Tried emptying out `.cache/peek` but that didn't help (same crash, and afterwards `.cache/peek` is still empty)

**Comment by phw** [comment] 2017-04-24 14:37
Seems to be a duplicate of #112 . The core of the issue seems to be ImageMagick convert having some issues with the "distributed pixel cache" (whatever this is). But the fact that it also affects the flatpak version puzzles me, because this comes with its own convert and I cannot reproduce the issue there.

I close this, please follow #112 for updates.

**Closed by phw** 2017-04-24 14:37 UTC
Labels: duplicate
