### ISSUE TITLE
Writing to file failed, caching issue?

### ISSUE THREAD

**Issue by orschiro** [phw/peek#139] opened 2017-05-18 04:51 UTC
Dear @phw, 

I may have finally found the problem I had encountered before that Peek would fail to create and write to the output file:

```
video:270730kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
convert-im6.q16: unable to get registry ID `cache:hosts' @ error/registry.c/GetImageRegistry/201.
convert-im6.q16: DistributedPixelCache '127.0.0.1' @ error/distribute-cache.c/ConnectPixelCacheServer/244.
convert-im6.q16: cache resources exhausted `/home/orschiro/.cache/peek/peekWBB2ZY.pam' @ error/cache.c/OpenPixelCache/3945.
Error: Child process exited with code 1
File save error: Error when getting information for file “/home/orschiro/.cache/peek/peekQ9RF0Y.gif”: No such file or directory
Temp file delete error: Error removing file /home/orschiro/.cache/peek/peekQ9RF0Y.gif: No such file or directory
```

**Comment by phw** [comment] 2017-05-22 08:39
You are on Ubuntu, right? Ubuntu sets really tight default resource limits for Ubuntu, see https://github.com/phw/peek/issues/112#issuecomment-296690302 and following comments for the issue and workarounds.

I will close this, as there are already enough tickets that are all related to the same root cause (imagemagick's resource usage). I will try to fix this, but I am currently too tight on time to work on it. I hope this will change soon.

**Closed by phw** 2017-05-22 08:39 UTC
Labels: duplicate

**Comment by orschiro** [comment] 2017-05-23 04:18
Thanks for your comment despite being a duplicate. 

I should have searched better.

Yes, I am on Ubuntu MATE at the moment. 

I look forward to addressing this problem! :-)
