### ISSUE TITLE
Mouse highlight on click (feature request)

### ISSUE THREAD

**Issue by ajulvestad** [phw/peek#615] opened 2020-06-25 08:00 UTC
I really like the simplicity here, and have used it a lot for helpdesk purposes.

One thing that would really help is some options to modify the cursor:
 1. A ring around the mouse cursor when moving around
 2. A graphical indication on screen that the mouse is clicked, like "find my mouse" animation when pressing CTRL on Gnome.

**Comment by taschetto** [comment] 2020-07-14 20:14
It would make instructional videos much more easy to follow. Great feature suggestion!

**Comment by jurgen-publiq** [comment] 2020-08-17 08:36
I tend to use key-mon as a tool for this. It adds a small keypress-area and allows to show mouse clicks. It could use some tender loving care, since it hasn't been updated since 2015. Still haven't found a comparable tool though.
https://github.com/critiqjo/key-mon

**Comment by YalandHong** [comment] 2020-12-28 11:40
Duplicate of #159 

And this problem has already appeared in FAQ:
https://github.com/phw/peek#how-can-i-capture-mouse-clicks-andor-keystrokes

I think the developers currently do not have any plan to implement this, although it is a very useful.

**Comment by rugk** [comment] 2021-02-16 20:02
Can you please close it as a dupe of #159? It's annoying to stumble on all these duplicate issues…

**Closed** 2021-02-16 20:19 UTC

**Comment by ajulvestad** [comment] 2021-02-16 20:21
Duplicate of #159
