### ISSUE TITLE
Just saving the background when using i3wm 

### ISSUE THREAD

**Issue by NikosEfthias** [phw/peek#57] opened 2017-01-01 18:12 UTC

**Comment by djmaze** [comment] 2017-01-09 17:56
Duplicate of #57

**Comment by phw** [comment] 2017-02-21 17:33
Sorry, missed this somehow. This sounds a lot like #12.

Do you have compositing enabled? Please note that there is a known issue with i3 which will not allow you to ineract with the UI inside the recording area.

**Comment by phw** [comment] 2017-02-28 15:48
Closing this as there is not enough information to pin this down. My best guess is that compositing was not enabled, see #12 and https://github.com/phw/peek#the-recording-area-is-all-black-how-can-i-record-anything . Feel free to re-open with additional details if compositing does not solve the issue.

**Closed by phw** 2017-02-28 15:48 UTC
Labels: bug, need-more-info
