### ISSUE TITLE
Ubuntu 16.04 / Peek 1.0.3 - Wrong desktop shortcut

### ISSUE THREAD

**Issue by bchauvin** [phw/peek#178] opened 2017-08-30 08:27 UTC
Hi,

Using Ubuntu 16.04 / Peek 1.0.3 with Unity desktop.
- Launch Peek
- Lock Peek to launcher
- Quit Peek
- Try to open Peek by clicking the launcher icon => you get a loading animation, then nothing happens

The problem is that when locking Peek to the launcher the desktop file generated contains:
`Exec=/usr/bin/peek --gapplication-service`

Removing the argument (using just a plain `/usr/bin/peek`) solves the issue.

Peek also appears twice in the application launcher, one entry seems to correspond to the behavior with the `--gapplication-service` and another launches the application as expected.  

I'm not sure if this is related to Unity or Peek, I used a previous Peek version in the past and did not encounter this issue.

**Comment by phw** [comment] 2017-08-30 08:36
That's DBUs activation being enabled for the app. Don't know why this is not working for you, never had any issues with it on Unity. Is there any output in `journalctl` when you try to start it?

**Comment by bchauvin** [comment] 2017-08-31 07:06
Nothing shows up when using the `--gapplication-service` argument.
When using the regular command: `com.uploadedlobster.peek[1445]: Using screen recorder backend ffmpeg`

I solved the issue by removing the `~/.local/share/applications/peek.desktop` entirely, now I only see a single entry and all went back to normal. Not really sure what happened but problem is solved.

**Comment by phw** [comment] 2017-08-31 07:34
Great this is solved. `~/.local/share/applications/peek.desktop` is a custom shortcut, this must have been manually created. It should not exist due to any official installation method. How did you install peek anyway?

**Comment by bchauvin** [comment] 2017-08-31 07:55
Thanks for your comment, it helped me understand where the issue comes from.

Steps to reproduce:
- Install Peek using Ubuntu PPA
=> At this point, Peek has a single entry in the dash

- Launch Peek
=> Works fine

- Right-click on Peek icon in the launcher
=> Several options are offered, including "Lock to launcher" and "Add to dash"

- Choose "Add to dash"
=> Two entries appear in the dash for Peek, one triggers Peek with the argument (leading to the behavior described previously), second launches Peek normally

- Launch Peek using second entry
=> Peek launches and works as expected

- Right click on launcher icon, choose "Lock to launcher"
- `sudo find / -name "peek.desktop"`
=> ~/.local/share/applications/peek.desktop

**Comment by bchauvin** [comment] 2017-08-31 08:01
Actually, just using the "Lock to launcher" option after starting Peek for the first time is sufficient to get the `~/.local/share/applications/peek.desktop` created.

**Comment by phw** [comment] 2017-08-31 08:03
That with lock to launcher makes sense. Never tested this, will have a look :)

**Comment by bchauvin** [comment] 2017-08-31 08:04
Agreed, that's very weird! Thanks for looking :)

FYI just using the "Lock to launcher" option after starting Peek for the first time is sufficient to get the `~/.local/share/applications/peek.desktop` created.

From there, you can do:
- `sudo apt purge peek`
- `sudo apt autoremove`
- `sudo find / -name "peek.desktop"`
=> `~/.local/share/applications/peek.desktop`

**Comment by phw** [comment] 2017-08-31 09:04
I cannot reproduce this in my Ubuntu 16.04 install with Unity. First I do not see the "Add to dash" entry (for none of the icons in my launcher). I have "Lock to launcher", which I can use and it works.

And never do I get any entry in `~/.local/share/applications/` or duplicate entries in the dash. Is your Ubuntu 16.04 up to date with the latest updates?

**Comment by phw** [comment] 2017-10-05 17:01
Closing, as I can neither reproduce this nor do I think this is a specific Peek issue. The desktop file is not special in any way, this looks rather like an issue of the launcher.

**Closed by phw** 2017-10-05 17:01 UTC
Labels: bug, cannot-reproduce
