### ISSUE TITLE
Fails to save recorded file

### ISSUE THREAD

**Issue by o-alquimista** [phw/peek#302] opened 2018-03-27 00:30 UTC
Description: When attempting to save the recorded file as a (GIF, WEBM and APNG) it doesn't ask me where to save it; instead it fails during processing with the following report:

Peek: 1.3.0
GTK: 3.22.26
GLib: 2.54.3

Details:
```
Command "ffmpeg -f x11grab -show_region 0 -framerate 10 -video_size 1356x604 -i :99.0+5,79 -filter:v scale=iw/1:-1 -codec:v libvpx-vp9 -qmin 10 -qmax 50 -crf 13 -b:v 1M -r 10 -y /home/alquimista/.var/app/com.uploadedlobster.peek/cache/peek/peekJ8TEGZ.webm" failed with status 256 (received signal 0).

Output:
ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers  built with gcc 6.2.0 (GCC)  configuration: --prefix=/app --disable-debug --disable-static --enable-gpl --enable-libvpx --enable-libx264 --enable-shared --enable-libxcb --enable-libxcb-xfixes --disable-libxcb-shape --disable-ffplay --disable-ffprobe --disable-ffserver --disable-doc --disable-everything --enable-decoder=libvpx_vp9 --enable-decoder=png --enable-decoder=rawvideo --enable-encoder=apng --enable-encoder=ffvhuff --enable-encoder=gif --enable-encoder=libvpx_vp9 --enable-encoder=libx264 --enable-encoder=png --enable-demuxer=image2 --enable-demuxer=matroska --enable-muxer=apng --enable-muxer=gif --enable-muxer=image2 --enable-muxer=mp4 --enable-muxer=webm --enable-filter=crop --enable-filter=fps --enable-filter=palettegen --enable-filter=paletteuse --enable-filter=scale --enable-protocol=file --enable-indev=xcbgrab  libavutil      55. 78.100 / 55. 78.100  libavcodec     57.107.100 / 57.107.100  libavformat    57. 83.100 / 57. 83.100  libavdevice    57. 10.100 / 57. 10.100  libavfilter     6.107.100 /  6.107.100  libswscale      4.  8.100 /  4.  8.100  libswresample   2.  9.100 /  2.  9.100  libpostproc    54.  7.100 / 54.  7.100[x11grab @ 0x151f700] Stream #0: not enough frames to estimate rate; consider increasing probesizeInput #0, x11grab, from ':99.0+5,79':  Duration: N/A, start: 1522110325.067289, bitrate: N/A    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1356x604, 10 fps, 1000k tbr, 1000k tbn, 1000k tbcStream mapping:  Stream #0:0 -> #0:0 (rawvideo (native) -> vp9 (libvpx-vp9))Press [q] to stop, [?] for help[libvpx-vp9 @ 0x1529100] v1.5.0Output #0, webm, to '/home/alquimista/.var/app/com.uploadedlobster.peek/cache/peek/peekJ8TEGZ.webm':  Metadata:    encoder         : Lavf57.83.100    Stream #0:0: Video: vp9 (libvpx-vp9), gbrp, 1356x604, q=10-50, 1000 kb/s, 10 fps, 1k tbn, 10 tbc    Metadata:      encoder         : Lavc57.107.100 libvpx-vp9    Side data:      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1Past duration 0.999916 too largeframe=    8 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
Past duration 0.999702 too largeframe=   13 fps= 13 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   19 fps= 12 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
Past duration 0.999977 too largePast duration 0.999550 too largeUnknown bitstream filter 'vp9_superframe'av_interleaved_write_frame(): Bitstream filter not foundframe=   25 fps= 11 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   25 fps=1.0 q=0.0 Lsize=       1kB time=00:00:00.00 bitrate=N/A speed=   0x    video:155kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknownConversion failed!
```

**Saving as MP4 works.**

This is a FLATPAK installation on top of Arch Linux. Desktop Env. is MATE 1.20 with default software compositing.

Previous Peek version worked. After latest update, issue appears.

**Comment by phw** [comment] 2018-03-28 13:33
Duplicate of #300 and #301

This is already fixed for the latest Flatpak. AppImage needs updating

**Closed by phw** 2018-03-28 13:33 UTC
Labels: duplicate
