### ISSUE TITLE
Ubutnu 17.04. Peek cannot write file

### ISSUE THREAD

**Issue by RokkerRuslan** [phw/peek#204] opened 2017-10-27 09:56 UTC
> :~ peek -v
> Peek 1.1.0

> :~ uname -a
> Linux rpc 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

> :~ peek
> Using screen recorder backend ffmpeg
> ffmpeg version 3.2.4-1build2 Copyright (c) 2000-2017 the FFmpeg developers
>   built with gcc 6.3.0 (Ubuntu 6.3.0-8ubuntu1) 20170221
>   configuration: --prefix=/usr --extra-version=1build2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
>   libavutil      55. 34.101 / 55. 34.101
>   libavcodec     57. 64.101 / 57. 64.101
>   libavformat    57. 56.101 / 57. 56.101
>   libavdevice    57.  1.100 / 57.  1.100
>   libavfilter     6. 65.100 /  6. 65.100
>   libavresample   3.  1.  0 /  3.  1.  0
>   libswscale      4.  2.100 /  4.  2.100
>   libswresample   2.  3.100 /  2.  3.100
>   libpostproc    54.  1.100 / 54.  1.100
> [x11grab @ 0x55a927d45fe0] Stream #0: not enough frames to estimate rate; consider increasing probesize
> Input #0, x11grab, from ':0+1935,87':
>   Duration: N/A, start: 1509098109.967989, bitrate: N/A
>     Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1391x579, 10 fps, 1000k tbr, 1000k tbn, 1000k tbc
> Output #0, rawvideo, to '/home/r/.cache/peek/peekXXXXXX.pam':
>   Metadata:
>     encoder         : Lavf57.56.101
>     Stream #0:0: Video: pam, rgb24, 1391x579, q=2-31, 200 kb/s, 10 fps, 10 tbn, 10 tbc
>     Metadata:
>       encoder         : Lavc57.64.101 pam
> Stream mapping:
>   Stream #0:0 -> #0:0 (rawvideo (native) -> pam (native))
> Press [q] to stop, [?] for help
> frame=  174 fps= 10 q=-0.0 Lsize=  410571kB time=00:00:17.40 bitrate=193298.5kbits/s speed=1.01x    
> video:410571kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
> convert-im6.q16: unable to get registry ID `cache:hosts' @ error/registry.c/GetImageRegistry/201.
> convert-im6.q16: DistributedPixelCache '127.0.0.1' @ error/distribute-cache.c/ConnectPixelCacheServer/244.
> convert-im6.q16: cache resources exhausted `/home/r/.cache/peek/peekXXXXXX.pam' @ error/cache.c/OpenPixelCache/3945.
> Error: Child process exited with code 1
> File save error: Error when getting information for file “/home/r/.cache/peek/peekXXXXXX.gif”: No such file or directory
> Temp file delete error: Error removing file /home/r/.cache/peek/peekXXXXXX.gif: No such file or directory

**Comment by gort818** [comment] 2017-10-28 00:00
Seems to be the same problem here #198

**Comment by phw** [comment] 2017-10-30 16:21
No, this is the typical "cache resource exhausted" error you get due to ImageMagick's excessive RAM usage.

@RokkerRuslan Peek 1.1.0 uses ImageMagick to convert the recorded videos to GIF files. I would recommend you to use the latest development version which does not use ImageMagick anymore and is lighter on resources. Easiest way for you is probably to switch to the daily PPA, see https://github.com/phw/peek/blob/master/README.md#ubuntu

Also see https://github.com/phw/peek/issues/196 for related discussion.

If you want to keep using Peek 1.1.0 stable some advice:

- Record smaller video (smaller screen area)
- Use the MP4 or WebM formats for recording
- Make sure you have enough free RAM available (I'd recommend at least 2-4 GB, but it's not easy to say how much ImageMagick will actually need).


Closing this as a duplicate of #125, #196 and others.

**Closed by phw** 2017-10-30 16:21 UTC
