### ISSUE TITLE
Recording misses most of the changes

### ISSUE THREAD

**Issue by linuxundich** [phw/peek#79] opened 2017-02-20 17:06 UTC
I'm trying to record a small gif with Peek 0.8.0 under Arch Linux. The result looks like the following image: You can see the mouse cursor moving, but you cant't see the text i'm entering and at the end i move the gedit window around. 

```
$ peek --version
Peek 0.8.0
$ peek
ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.1 (GCC) 20170109
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-netcdf --enable-shared --enable-version3 --enable-x11grab
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, x11grab, from ':0+977,135':
  Duration: N/A, start: 1487609922.891240, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 672x398, 15 fps, 15 tbr, 1000k tbn, 1000k tbc
[huffyuv @ 0x55a83e023380] using huffyuv 2.2.0 or newer interlacing flag
[huffyuv @ 0x55a83e028460] using huffyuv 2.2.0 or newer interlacing flag
[huffyuv @ 0x55a83e02af80] using huffyuv 2.2.0 or newer interlacing flag
[huffyuv @ 0x55a83e02dec0] using huffyuv 2.2.0 or newer interlacing flag
[huffyuv @ 0x55a83e000900] using huffyuv 2.2.0 or newer interlacing flag
Output #0, avi, to '/tmp/peek5YFMVY.avi':
  Metadata:
    ISFT            : Lavf57.56.101
    Stream #0:0: Video: huffyuv (HFYU / 0x55594648), rgb24, 672x398, q=2-31, 200 kb/s, 15 fps, 15 tbn, 15 tbc
    Metadata:
      encoder         : Lavc57.64.101 huffyuv
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> huffyuv (native))
Press [q] to stop, [?] for help
frame=   14 fps=0.0 q=-0.0 size=    2227kB time=00:00:00.66 bitrate=27365.1kbitsframe=   22 fps= 21 q=-0.0 size=    4003kB time=00:00:01.20 bitrate=27330.2kbitsframe=   30 fps= 19 q=-0.0 size=    5780kB time=00:00:01.73 bitrate=27315.0kbitsframe=   38 fps= 18 q=-0.0 size=    7556kB time=00:00:02.26 bitrate=27308.0kbitsframe=   46 fps= 17 q=-0.0 size=    9332kB time=00:00:02.80 bitrate=27303.5kbitsframe=   54 fps= 17 q=-0.0 size=   11109kB time=00:00:03.33 bitrate=27300.6kbitsframe=   62 fps= 17 q=-0.0 size=   12885kB time=00:00:03.86 bitrate=27298.2kbitsframe=   70 fps= 16 q=-0.0 size=   14661kB time=00:00:04.40 bitrate=27296.5kbitsframe=   78 fps= 16 q=-0.0 size=   16438kB time=00:00:04.93 bitrate=27295.2kbitsframe=   86 fps= 16 q=-0.0 size=   18214kB time=00:00:05.46 bitrate=27294.1kbitsframe=   94 fps= 16 q=-0.0 size=   19990kB time=00:00:06.00 bitrate=27293.3kbitsframe=  102 fps= 16 q=-0.0 size=   21766kB time=00:00:06.53 bitrate=27292.2kbitsframe=  110 fps= 16 q=-0.0 size=   23543kB time=00:00:07.06 bitrate=27292.2kbitsframe=  118 fps= 16 q=-0.0 size=   25321kB time=00:00:07.60 bitrate=27293.4kbitsframe=  126 fps= 16 q=-0.0 size=   27100kB time=00:00:08.13 bitrate=27295.1kbitsframe=  134 fps= 16 q=-0.0 size=   28878kB time=00:00:08.66 bitrate=27296.3kbitsframe=  142 fps= 16 q=-0.0 size=   30656kB time=00:00:09.20 bitrate=27297.6kbitsframe=  150 fps= 16 q=-0.0 size=   32435kB time=00:00:09.73 bitrate=27298.7kbitsRecording stopped 
frame=  157 fps= 16 q=-0.0 Lsize=   34882kB time=00:00:10.46 bitrate=27301.2kbits/s speed=1.03x    
video:34873kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.026772%

(peek:3038): GLib-GIO-CRITICAL **: g_file_delete_finish: assertion 'G_IS_FILE (file)' failed
```
![peek 2017-02-20 17-58](https://cloud.githubusercontent.com/assets/1716643/23134932/eb679ef6-f796-11e6-8a3f-eedacc5e551c.gif)

**Comment by phw** [comment] 2017-02-20 18:32
That's very strange indeed. Looks a bit like #51, but I cannot reproduce (also on Arch).

Some ideas to debug:

- Try using the latest git revision of Peek, I changed the recording a bit.
- Try recording directly with ffmpeg, does this produce a working video?
- It could be a video driver issue, what are you using?
- Does other screen recording work?
- Is this on a physical machine or inside a VM?

**Comment by phw** [comment] 2017-02-20 23:00
I have released version 0.9 and update the AUR package, so this is maybe the easiest way to verify whether this newer version works or not. Otherwise some more info as asked above could probably help to pint this down

**Comment by linuxundich** [comment] 2017-02-21 10:59
Hi phw, I installed version 0.9, but the prioblem remains. Here are some basic informations about my system here:

```
$ inxi -F
System:    Host: isleofskye Kernel: 4.9.11-1-ARCH x86_64 (64 bit) Desktop: Gnome 3.22.3 Distro: Arch Linux
Machine:   Device: desktop Mobo: N/A model: N/A BIOS: American Megatrends v: 080015 date: 08/13/2010
CPU:       Dual core Intel Core i3 530 (-HT-MCP-) cache: 4096 KB 
           clock speeds: max: 2933 MHz 1: 1200 MHz 2: 1200 MHz 3: 1200 MHz 4: 1200 MHz
Graphics:  Card: Intel Core Processor Integrated Graphics Controller
           Display Server: X.Org 1.19.1 driver: intel Resolution: 1920x1080@59.93hz, 1280x1024@60.02hz
           GLX Renderer: Mesa DRI Intel Ironlake Desktop GLX Version: 2.1 Mesa 17.0.0
Audio:     Card Intel 5 Series/3400 Series High Definition Audio driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.9.11-1-ARCH
Network:   Card-1: Intel 82578DM Gigabit Network Connection driver: e1000e
           IF: enp0s25 state: up speed: 1000 Mbps duplex: full mac: 00:01:2e:2f:fb:d4
           Card-2: Ralink RT2790 Wireless 802.11n 1T/2R PCIe driver: rt2800pci
           IF: wls128 state: down mac: 7e:c1:5d:42:77:5a
Drives:    HDD Total Size: 720.2GB (25.9% used)
           ID-1: /dev/sda model: SanDisk_SDSSDP06 size: 64.0GB
           ID-2: /dev/sdb model: SAMSUNG_HM641JI size: 640.1GB
           ID-3: USB /dev/sdc model: STORAGE_DEVICE size: 16.0GB
Partition: ID-1: / size: 53G used: 29G (57%) fs: ext4 dev: /dev/sda1
           ID-2: /home size: 587G used: 140G (26%) fs: ext4 dev: /dev/sdb1
           ID-3: swap-1 size: 6.35GB used: 2.98GB (47%) fs: swap dev: /dev/sda2
Sensors:   System Temperatures: cpu: 46.0C mobo: 28.0C
           Fan Speeds (in rpm): cpu: N/A fan-1: 0 fan-2: 629 fan-3: 0 fan-4: 0 fan-5: 0
Info:      Processes: 250 Uptime: 1:24 Memory: 741.7/3631.4MB Client: Shell (bash) inxi: 2.3.8 
```

But it looks like it's related to every recording software. I've got the same problem with SimpleScreenRecorder. So i guess, we can close this one, since there's a deeper problem with my system here.

**Comment by phw** [comment] 2017-02-21 17:18
Ok, strange anyway. My best bet is still on the Intel driver. You could try switching between UXA and SNA acceleration methods (see the Arch wiki), change from whatever you are using now to the other option and see if this helps. In my experience this often helps in issues like that.

Another option would be to install the latest master from Peek. I have added a new gnome-shell backend which will use the screen recording provided by Gnome Shell via DBus. Maybe that works better (and it will also work on a Gnome Wayland session).

**Comment by phw** [comment] 2017-02-22 09:19
I am closing this, feel free to reopen if you have more information.

**Closed** 2017-02-22 09:21 UTC
Labels: bug
