### ISSUE TITLE
convert never finished

### ISSUE THREAD

**Issue by xstable** [phw/peek#101] opened 2017-03-10 13:23 UTC
I start peek and Record my stuff.
If I click stop, my i7 with 12GB RAM nearly freeze. 

If I open the Taskmanager, I see this process:
![auswahl_254](https://cloud.githubusercontent.com/assets/1778068/23796717/c554318e-059c-11e7-9ea0-bbda60dd1bc7.jpg)

But this process seems not to finshed ever. I have tried it for 5 Minutes (or a bit more).
If I check the peek.....avi File in tmp, it has 2MB, and can be played without any issues: see the zip-file:
[peekEZC8WY.zip](https://github.com/phw/peek/files/834004/peekEZC8WY.zip)

**Comment by phw** [comment] 2017-03-10 13:47
Can you try running `convert -set delay 15 -layers Optimize peekEZC8WY.avi peekEZC8WY.gif` on that file? Finished for me in under a minute.

Also please try the latest master release, there has been changes to how the recording works, which requires less work for convert.

If it still does not work please give some more details about what OS you use and which version of ImageMagick and ffmpeg this is.

**Comment by xstable** [comment] 2017-03-10 14:49
This command `convert -set delay 15 -layers Optimize peekEZC8WY.avi peekEZC8WY.gif` works... also under a minute.

**Comment by brw** [comment] 2017-03-14 22:47
Exact issue here on 1.0.0. Worked fine two weeks ago.

**Comment by phw** [comment] 2017-03-16 07:17
Can you guys test the latest from git master and run it from command line with:

  PEEK_MAGICK_DEBUG=All 

Then give me the output. And please give some more info about your system, especially what OS and which version of ImageMagivk is used.

**Comment by brw** [comment] 2017-03-16 14:23
OS: Arch Linux
ImageMagick version: 6.9.8.0-1
```
❯ uname -a
Linux bacon 4.10.2-1-ARCH #1 SMP PREEMPT Mon Mar 13 17:13:41 CET 2017 x86_64 GNU/Linux
```
Log: http://pastebin.com/DQPBTHeH

**Comment by phw** [comment] 2017-03-16 15:46
@brw Nothing unusual here. How large was the screen area you have been recording, and for how long did you record? The conversion can take quite some time, and convert allocates a lot of memory quickly (depending on how much RAM you have). When convert is running, does your system start swapping?

Does this happen all of the time or only for some recordings? Does lowering the size / time / framerate help?

**Comment by brw** [comment] 2017-03-16 22:31
Recorded almost my whole screen (1700x700 or something), tried it a few times with a duration of 15 seconds up to a minute, my system does start swapping.
But yea, didn't think of just making it smaller or shorter, works fine that way now, so it's just the conversion my 8GB of RAM is not able to handle ¯\_(ツ)_/¯.
I did have the issue of it not stopping with converting at all at first (not even after having waited for 30 minutes for a very short recording, basically freezing my system) but it looks like I might have accidentally used the latest release instead of the latest master when I thought I wasn't, so that doesn't seem to be a problem anymore.

**Comment by phw** [comment] 2017-03-17 19:29
I really think we are talking about memory issues here (also for the original problem reported). The main problem with Peek before 1.0 was, that it was storing temporary files in /tmp. Now in many distributions /tmp is actually a RAM disk.

Now convert uses both /tmp by default *and* allocates a lot of memory, especially for the optimization of the GIF. It actually takes the memory based on what is available (in one test for the same file convert used roughly 4 GB on an 8 GB system, but nearly 9 GB on my 16 GB laptop). But if you also fill the /tmp RAM disk with several hundred megabytes of image frames this competes with the RAM usage and you quickly get into swapping.

Next thing would be to investigate to limit the RAM imagemagick uses. You can override its resource usage, but I probably have to be clever about it. Needs some testing with what we can get away for typical GIF conversion.

> Recorded almost my whole screen (1700x700 or something), tried it a few times with a duration of 15 seconds up to a minute, my system does start swapping.

GIF is really not the right format for such large resolutions. The result will be huge. Also recording length should be short, definitely under a minute. For larger and / or longer recordings I would recommend using the WebM or MP4 format also supported.

**Comment by VoLuong** [comment] 2017-04-06 15:11
I can confirm this issue on Xubuntu 16.04.2 and latest version of Peek

**Comment by xstable** [comment] 2017-04-06 15:20
Last record worked like a charm now on Manjaro-Linux.

**Comment by phw** [comment] 2017-11-16 17:33
I am going to close this issue. As the recording was significantly refactored for the upcoming 1.2 release I think this should be fixed. Please try out the latest development version. If you still encounter problems with recording feel free to open a new issue.

**Closed by phw** 2017-11-16 17:33 UTC
Labels: bug, need more info
