### ISSUE TITLE
Neither snap nor flatpack are working in Fedora 26 with KDE

### ISSUE THREAD

**Issue by RomuloPBenedetti** [phw/peek#184] opened 2017-09-24 21:05 UTC
The snap version keeps asking for connection even after executing the appointed commands, and the flatpak version simply did not save files. :) Anyway, the old-fashioned dnf works.

**Comment by phw** [comment] 2017-09-25 06:18
Flatpak should work, can you give details on the error when you run it from console? It is likely you run into https://github.com/phw/peek/issues/11

When did you try installing the Snap? Current version should work, the version up on edge a couple of days ago would have the issue you described. In general the snap support is experimental and changes currently.

You can also try the beta channel, which is reported to work:

      So
snap install peek --beta

**Comment by RomuloPBenedetti** [comment] 2017-09-25 06:36
console gives nothing, it shows ffmpeg logging, and when I click in "save" it did not save and nothing is printed to console, the strange part is that the file manager from Peek shows the old saved file if I try to save another record, but dolphin and ls show the file did not exist.

**Comment by phw** [comment] 2017-09-25 07:12
Sounds like a file permission issue to me. Did you install Peek Flatpak from flathub or following the instructions in the README (which uses my own Flatpak repository)?

Could you try installing the latest master release via 

    flatpak install --user http://flatpak.uploadedlobster.com/peek-mastet.flatpakref

And run that with

    flatpak run com.uploadedlobster.peek//master

I fixed a file permission issue there, might be related. Thanks a lot for reporting :)

**Comment by phw** [comment] 2017-10-05 16:59
I have put out a new release with updated Snap and Flatpak packages. Could you try those (please see the updated Snap install instructions in the README)?

I cannot reproduce this issue at all, but I think this is related to the file permission bug Peek had before the 1.1.0 release.

**Comment by phw** [comment] 2017-10-12 07:41
Closing for now, as I expect the packages to work. Please let me know if there are still issues and I will reopen this.

**Closed by phw** 2017-10-12 07:41 UTC
