### ISSUE TITLE
Peek Does Not Open

### ISSUE THREAD

**Issue by nebutron** [phw/peek#124] opened 2017-03-28 18:21 UTC
I am using the latest version of Peek from the AUR. I am running the latest Antergos Linux. The version would be 1.0.1-1.

I click on the icon and it shows a loading animation for my mouse for a bit, then nothing. It does not run at all.

If I install the developer version, it does run just fine.

Where can I find some logs for it, I can then attach that for you?

**Comment by phw** [comment] 2017-03-29 04:19
Please try running Peek from command line and see if it starts here. If that works but starting from shortcut does not, have a look at the output of "journalctl -f" while starting Peek

**Comment by phw** [comment] 2017-04-06 09:07
I tried to reproduce this and opened and installed peek instead of peek-git on my Arch. But for both installs Peek opens just fine via desktop shortcut. It would be great if you could try this again, and if it still does not open please give the output as asked above.

Otherwise I will write this off as a temporary glitch with desktop files on your install and close this.

**Comment by nebutron** [comment] 2017-04-06 12:43
Haven't had a chance as I do need to use Peek during the week. I will try to get this tested this weekend and let you know. If not, I will let you know and you can close it.

**Comment by SalahAdDin** [comment] 2017-04-13 08:56
With new version in Antergos i have the same problem: I do click in the `peek` icon but `peek` doesn't init.

But if i'll go to the terminal and put `peek`, `enter`,  `peek` inits corretly.

What happen @phw ?

**Comment by phw** [comment] 2017-04-13 08:58
No idea, please run `"journalctl -f`, then try opening Peek via desktop shortcut and give the journaloutput here. Also please tell me the desktop environment used.

**Comment by SalahAdDin** [comment] 2017-04-13 09:29
Here is the traceback:
```bash
abr 13 12:28:27 TulipanROG dleyna-renderer-service[29465]: Enabled : F
abr 13 12:28:27 TulipanROG dleyna-renderer-service[29465]: Entries: (null)
abr 13 12:28:27 TulipanROG dleyna-renderer-service[29465]: Calling GetRenderers method
abr 13 12:28:27 TulipanROG dleyna-renderer-service[29465]: Client :1.1433 lost
abr 13 12:28:29 TulipanROG dleyna-renderer-service[29465]: dLeyna: Exit
abr 13 12:28:29 TulipanROG dbus-daemon[1100]: Activating service name='com.uploadedlobster.peek'
abr 13 12:28:29 TulipanROG dbus-daemon[1100]: Activated service 'com.uploadedlobster.peek' failed: Failed to execute program com.uploadedlobster.peek: No such file or directory
abr 13 12:28:33 TulipanROG shutter.desktop[27755]: GdkPixbuf-LOG **: gdk_pixbuf_from_pixdata() called on: at /usr/bin/shutter line 2891.
abr 13 12:28:33 TulipanROG shutter.desktop[27755]: GdkPixbuf-LOG **:         Encoding raw at /usr/bin/shutter line 2891.
abr 13 12:28:33 TulipanROG shutter.desktop[27755]: GdkPixbuf-LOG **:         Dimensions: 16 x 16 at /usr/bin/shutter line 2891.
abr 13 12:28:33 TulipanROG shutter.desktop[27755]: GdkPixbuf-LOG **:         Rowstride: 64, Length: 1048 at /usr/bin/shutter line 2891.
abr 13 12:28:33 TulipanROG shutter.desktop[27755]: GdkPixbuf-LOG **:         Copy pixels == false at /usr/bin/shutter line 2891.
abr 13 12:28:33 TulipanROG shutter.desktop[27755]: GdkPixbuf-LOG **: gdk_pixbuf_from_pixdata() called on: at /usr/bin/shutter line 2891.
abr 13 12:28:33 TulipanROG shutter.desktop[27755]: GdkPixbuf-LOG **:         Encoding raw at /usr/bin/shutter line 2891.
abr 13 12:28:33 TulipanROG shutter.desktop[27755]: GdkPixbuf-LOG **:         Dimensions: 16 x 16 at /usr/bin/shutter line 2891.
abr 13 12:28:33 TulipanROG shutter.desktop[27755]: GdkPixbuf-LOG **:         Rowstride: 64, Length: 1048 at /usr/bin/shutter line 2891.
abr 13 12:28:33 TulipanROG shutter.desktop[27755]: GdkPixbuf-LOG **:         Copy pixels == false at /usr/bin/shutter line 2891.
```

**Comment by phw** [comment] 2017-04-13 09:40
@SalahAdDin There is something messed up with DBus activation. Can you give me the following information:

- What desktop environment is this?
- Can you give me the contents of `/usr/share/dbus-1/services/com.uploadedlobster.peek.service`?

As a workaround you might comment out DBusActivatable in the com.uploadedlobser.peek.desktop file, but please give me the above information nevertheless.

**Comment by SalahAdDin** [comment] 2017-04-13 10:50
I'm working in `Antergos Linux 64Bits`.

here is the content:
```
[D-BUS Service]
Name=com.uploadedlobster.peek
Exec=/pkg/pkg/peek/usr/bin/peek --gapplication-service
```

**Comment by phw** [comment] 2017-04-13 11:38
That's the wrong path there. I went digging and found https://github.com/Antergos/antergos-packages/blob/master/antergos/peek/PKGBUILD , which seems to be the PKGBUILD for the Antergos package. It is broken, the `CMAKE_INSTALL_PREFIX` should be set to `/usr`, not `${pkgdir}/usr`

I have reported this issue on https://github.com/Antergos/antergos-packages/issues/180

In the meantime I would suggest you install the peek package from https://aur.archlinux.org/packages/peek/ , that has a proper working PKGBUILD.

**Comment by SalahAdDin** [comment] 2017-04-13 11:45
I tried with `AUR` package:
```
abr 13 14:44:41 TulipanROG dleyna-renderer-service[16725]: Port: 0
abr 13 14:44:41 TulipanROG dleyna-renderer-service[16725]: Push host port: 0
abr 13 14:44:41 TulipanROG dleyna-renderer-service[16725]: [Logging settings]
abr 13 14:44:41 TulipanROG dleyna-renderer-service[16725]: Log Type : 0
abr 13 14:44:41 TulipanROG dleyna-renderer-service[16725]: Log Level: 0x13
abr 13 14:44:41 TulipanROG dleyna-renderer-service[16725]: [Network filtering settings]
abr 13 14:44:41 TulipanROG dleyna-renderer-service[16725]: Enabled : F
abr 13 14:44:41 TulipanROG dleyna-renderer-service[16725]: Entries: (null)
abr 13 14:44:41 TulipanROG dleyna-renderer-service[16725]: Calling GetRenderers method
abr 13 14:44:41 TulipanROG dleyna-renderer-service[16725]: Client :1.536 lost
abr 13 14:44:41 TulipanROG dleyna-renderer-service[16254]: dLeyna: Exit
abr 13 14:44:42 TulipanROG dleyna-renderer-service[16725]: dLeyna: Exit
abr 13 14:44:42 TulipanROG dbus-daemon[1071]: Activating service name='com.uploadedlobster.peek'
abr 13 14:44:42 TulipanROG dbus-daemon[1071]: Activated service 'com.uploadedlobster.peek' failed: Failed to execute program com.uploadedlobster.peek: No such file or directory
```

Same problem, and worst.

**Comment by phw** [comment] 2017-04-13 11:47
Can you please give me the content of /usr/share/dbus-1/services/com.uploadedlobster.peek.service again? Also the output of makepkg when you built peek would help a lot.

**Comment by SalahAdDin** [comment] 2017-04-13 12:03
```
[D-BUS Service]
Name=com.uploadedlobster.peek
Exec=/pkg/pkg/peek/usr/bin/peek --gapplication-service
```

**Comment by phw** [comment] 2017-04-13 12:07
Thanks for testing this. I am very sure you are still running the Antergos package. If you installed it with e.g. yaourt, it will prefer binary packages in official repositories. And since there is an Antergos package it will use that. The output of `pacman -Qi peek` could confirm this. If the description is "An animated GIF recorder." it is the Antergos package. Also the build time would be older, if you just installed the AUR package the build time will be current.

**Comment by SalahAdDin** [comment] 2017-04-13 12:33
I reinstalled from `AUR`: `yaourt -Sbu peek`.

**Comment by phw** [comment] 2017-04-13 13:16
> I reinstalled from AUR: yaourt -Sbu peek.

Are you sure it installed from AUR? Since the package peek is in the Antergos repos this will not install from AUR, yaourt will prefer the repo package. Did yaourt ask you to review the PKBUILD? If yes, please do and double check it is the correct one.

**Comment by SalahAdDin** [comment] 2017-04-13 22:56
Now, didn't It, you are right.

**Comment by phw** [comment] 2017-04-18 08:02
I am closing this issue. The PKGBUILD for Antergos has been updated and there was a rebuild of the package, see http://build.antergos.com/build/6275.

Not sure why the PKGBUILD specifies version 1.0.1-2, but the built package is displayed as 1.0.1-1. If in doubt uninstall and reinstall the package

**Closed by phw** 2017-04-18 08:02 UTC
Labels: packaging

**Comment by SalahAdDin** [comment] 2017-04-18 08:25
Yep, is solved. Thank you!
