### ISSUE TITLE
Gif error

### ISSUE THREAD

**Issue by sweatC** [phw/peek#301] opened 2018-03-26 19:07 UTC
Peek: 1.3.0
GTK: 3.22.26
GLib: 2.54.3

Details:
```
Command "ffmpeg -f x11grab -show_region 0 -framerate 10 -video_size 319x570 -i :99.0+508,62 -filter:v scale=iw/1:-1 -codec:v libvpx-vp9 -lossless 1 -r 10 -y /home/sweatc/.var/app/com.uploadedlobster.peek/cache/peek/peekOLRKGZ.webm" failed with status 256 (received signal 0).

Output:
ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers  built with gcc 6.2.0 (GCC)  configuration: --prefix=/app --disable-debug --disable-static --enable-gpl --enable-libvpx --enable-libx264 --enable-shared --enable-libxcb --enable-libxcb-xfixes --disable-libxcb-shape --disable-ffplay --disable-ffprobe --disable-ffserver --disable-doc --disable-everything --enable-decoder=libvpx_vp9 --enable-decoder=png --enable-decoder=rawvideo --enable-encoder=apng --enable-encoder=ffvhuff --enable-encoder=gif --enable-encoder=libvpx_vp9 --enable-encoder=libx264 --enable-encoder=png --enable-demuxer=image2 --enable-demuxer=matroska --enable-muxer=apng --enable-muxer=gif --enable-muxer=image2 --enable-muxer=mp4 --enable-muxer=webm --enable-filter=crop --enable-filter=fps --enable-filter=palettegen --enable-filter=paletteuse --enable-filter=scale --enable-protocol=file --enable-indev=xcbgrab  libavutil      55. 78.100 / 55. 78.100  libavcodec     57.107.100 / 57.107.100  libavformat    57. 83.100 / 57. 83.100  libavdevice    57. 10.100 / 57. 10.100  libavfilter     6.107.100 /  6.107.100  libswscale      4.  8.100 /  4.  8.100  libswresample   2.  9.100 /  2.  9.100  libpostproc    54.  7.100 / 54.  7.100Input #0, x11grab, from ':99.0+508,62':  Duration: N/A, start: 1522091120.241028, bitrate: N/A    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 319x570, 10 fps, 10 tbr, 1000k tbn, 1000k tbcStream mapping:  Stream #0:0 -> #0:0 (rawvideo (native) -> vp9 (libvpx-vp9))Press [q] to stop, [?] for help[libvpx-vp9 @ 0x1b8b3e0] v1.5.0Output #0, webm, to '/home/sweatc/.var/app/com.uploadedlobster.peek/cache/peek/peekOLRKGZ.webm':  Metadata:    encoder         : Lavf57.83.100    Stream #0:0: Video: vp9 (libvpx-vp9), gbrp, 319x570, q=-1--1, 200 kb/s, 10 fps, 1k tbn, 10 tbc    Metadata:      encoder         : Lavc57.107.100 libvpx-vp9    Side data:      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1frame=   14 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   19 fps= 17 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   24 fps= 15 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
Unknown bitstream filter 'vp9_superframe'av_interleaved_write_frame(): Bitstream filter not foundframe=   25 fps=6.5 q=0.0 Lsize=       1kB time=00:00:00.00 bitrate=N/A speed=   0x    video:41kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknownConversion failed!
```

**Comment by phw** [comment] 2018-03-26 20:29
I will fix this in the AppImage and Flatpak builds (both are affected). The builds should be available tomorrow. I close this as a duplicate of #300 for now.

**Closed by phw** 2018-03-26 20:29 UTC
Labels: bug, duplicate
