### ISSUE TITLE
Warning on compillation 

### ISSUE THREAD

**Issue by luzpaz** [phw/peek#241] opened 2017-12-03 16:38 UTC
Built on Manjaro 17.1pre3 built using latest [peek-git AUR package](https://aur.archlinux.org/packages/peek-git/)
```
[  5%] Building C object CMakeFiles/peek.dir/src/application.c.o
/tmp/pamac-build-beast/peek-git/src/build/src/application.c: In function ‘peek_application_show_wayland_warning’:
/tmp/pamac-build-beast/peek-git/src/build/src/application.c:1009:118: warning: zero-length gnu_printf format string [-Wformat-zero-length]
 mp3_ = (GtkMessageDialog*) gtk_message_dialog_new (_tmp2_, GTK_DIALOG_MODAL, GTK_MESSAGE_WARNING, GTK_BUTTONS_OK, "");
```                                                                                                                   ^~

**Comment by phw** [comment] 2017-12-03 16:48
Yes, I am aware of this, but I don't know how to avoid it :(

The problem is in C you could just give `NULL` to the call of [gtk-message-dialog-new](https://developer.gnome.org/gtk3/stable/GtkMessageDialog.html#gtk-message-dialog-new). But if you pass `null` in Vala it actually calls `gtk-message-dialog-new` with `"%s"`. I think this is a bug in the Vala bindings I can't don anything about in Peek.

**Comment by luzpaz** [comment] 2017-12-03 16:50
Thanks for the explanation and also thank you for this cool program. Cheers!

**Comment by phw** [comment] 2017-12-03 16:53
Thanks, happy you enjoy it. I keep this issue open and report it to Vala as soon as I have some more time for it.

**Comment by phw** [comment] 2017-12-04 16:47
https://bugzilla.gnome.org/show_bug.cgi?id=791215

**Comment by phw** [comment] 2017-12-06 19:12
A fix for this is now in the Vala repository (https://git.gnome.org/browse/vala/commit/?id=84c8584). So starting with the next Vala release cleaner code will be generated and these warnings should go away.

**Comment by phw** [comment] 2017-12-06 19:50
Ups, reopening. Forgot that I still have to change the code to use `null` instead of `""`. I will do this once a new Vala release is out and I can test it. This will make the warning even more ugly for older Vala versions, though, but it's cleaner in general.

**Comment by phw** [comment] 2017-12-13 12:30
New version introduced another issue, but worked around the warning for now.

**Closed** 2017-12-13 12:29 UTC
Labels: bug, upstream
