### ISSUE TITLE
Saving recording fails on Gnome Shell with Xorg

### ISSUE THREAD

**Issue by sevaivanov** [phw/peek#93] opened 2017-03-02 23:52 UTC
Here is a [log](http://sprunge.us/ZJLD). Tell me if you need more info! :octopus:

**Comment by phw** [comment] 2017-03-05 12:34
Not sure what is happening here, as I am also running on Arch. ffmpeg seems to have recorded the video, but then convert fails (which will call ffmpeg again):

    convert: delegate failed `'ffmpeg' -nostdin -v -1 -i '%i' -vframes %S -vcodec pam -an -f rawvideo -y '%u.pam' 2> '%u'' @ error/delegate.c/InvokeDelegate/1919.

I am unhappy anyway about convert needing to decode the video again and will likely switch over to capturing the frames separately.

**Comment by phw** [comment] 2017-03-09 16:40
Can you give latest git revision a try?

I have committed a change that avoids  the re-encoding of the video by convert if ffmpeg was used. For the new gnome-shell backend this does not yet work. But I also changed the location of the intermediary files to be inside /home, memory issues with /tmp could very well have been the cause for your problem.

**Comment by phw** [comment] 2017-03-09 19:12
I finally uploaded the peek-git PKGBUILD to the AUR, maybe the most convenient method to test the latest version: https://aur.archlinux.org/packages/peek-git/

**Comment by sevaivanov** [comment] 2017-03-10 00:34
Thank you for the swift response.

I tried recording and good news, everything works! I absolutely love the simplicity of the usage.

Perhaps, the other non-```peek-git``` packages should be flagged outdated to avoid confusion. Otherwise, there seems to be a very high peek in the CPU (laptop freeze) during the rendering stage but once finished, everything is back to normal. Maybe it is not related to the software.

**Closed** 2017-03-10 00:34 UTC
Labels: bug

**Comment by phw** [comment] 2017-03-10 13:49
> Perhaps, the other non-peek-git packages should be flagged outdated to avoid confusion.

No, it should not as it is not outdated. The peek package is the latest release and will be updated when there is a new release. peek-git installs the latest revision from git and is for people who want to use the latest development version.

**Comment by Skylsmoi** [comment] 2017-04-21 10:15
I think I have the same issue on debian
```
Using screen recorder backend gnome-shell
Recording to file /home/come/.cache/peek/peekF5XVYY.mp4
convert: delegate failed `"ffmpeg" -v -1 -i "%i" -vframes %S -vcodec pam -an -f rawvideo -y "%u.pam" 2> "%Z"' @ error/delegate.c/InvokeDelegate/1310.
convert: unable to open image `/home/come/.cache/peek/magick-21081jTiiLtLHVsyp.pam': Aucun fichier ou dossier de ce type @ error/blob.c/OpenBlob/2712.
convert: no images defined `/home/come/.cache/peek/peek7848YY.gif' @ error/convert.c/ConvertImageCommand/3210.
Error: Le processus fils s'est terminé avec le code 1
Temp file delete error: Erreur à la suppression du fichier : Aucun fichier ou dossier de ce type
```
Can you provide a similar fix for debian please ?

**Comment by phw** [comment] 2017-04-21 10:25
@Skylsmoi No, your error is different. Do you gave ffmpeg or avconv installed? Make sure ffmpeg is working. If your issues isn't solved by this please open a new issue here.

**Comment by Skylsmoi** [comment] 2017-04-21 10:59
indeed, ffmpeg wasn't installed.
It now works fine ! thank you for your quick help

Maybe you should add ffmpeg in the dependencies list in the debian install section
