### ISSUE TITLE
Error in gif output

### ISSUE THREAD

**Issue by ni-ka** [phw/peek#305] opened 2018-04-05 16:29 UTC
Using gnome 3.28 on arch, wayland and screen scaling active (125%) as I am on a WQHD display
![peek 2018-04-05 09-27](https://user-images.githubusercontent.com/1225776/38378852-c9a8f1ca-38b3-11e8-9151-4bfe4137b89c.gif)

**Comment by phw** [comment] 2018-04-10 13:39
I cannot replicate this, but I also have no WQHD display to test and cannot set a 125% scaling here.

Nevertheless, since Peek just uses the builtin screen recording of Gnome Shell this is most likely an upstream issue. What happens if you use the built in screen recording (triggered by `Ctrl` + `Shift` + `Alt` + R by default)?

On X11 you could fall back to using Peek with the ffmpeg backend by starting it with `peek -b ffmpeg`.

**Comment by phw** [comment] 2018-04-12 08:02
Actually this is a duplicate of #268, which also has an upstream bug report.

**Closed by phw** 2018-04-12 08:02 UTC
Labels: upstream
