### ISSUE TITLE
mouse/interaction with recording area

### ISSUE THREAD

**Issue by mephux** [phw/peek#52] opened 2016-12-06 19:08 UTC
Example: Recording a form and clicking the submit button is not possible outside of using the keyboard.

Any plans to support something like this. I'm currently reading over the code to see how complex it would be to contribute.

Thanks for a great project.

**Comment by phw** [comment] 2016-12-06 19:32
Do you mean when clicking into the recording area does not allow you to interact with the application behind Peek? This is absolutely supposed to work, if not it is a bug.

At issue #12 some people are reporting this does not work under i3. But it could also be related to the Gtk version used.

What desktop environment and window manager are you using? Which version of Gtk?

**Comment by mephux** [comment] 2016-12-06 20:31
@phw ah, makes sense. I am using i3. I'll look into it and see if I can figure it out and submit a PR.

**Comment by mephux** [comment] 2016-12-06 20:50
@phw gtk 3.22.4-1

**Comment by ibrahima** [comment] 2016-12-06 20:57
I'm experiencing this with AwesomeWM+Compton, on 3.18.9-1ubuntu3.1 (Ubuntu 16.04, fully patched).

My suspicion is that the way tiling managers work and/or the interaction with Compton is preventing the clicks from going through to the background application. There might be particular window state/flags that makes it work for you; with Awesome, if I start recording, and then send the Peek window to the background, I can interact with the application that I want to record, but if it's supposed to actually click through to the application behind it then that might require specific support for tiling WMs. For Awesome, I tried to set up rules for the Peek application so that it is floating but not always on top, but I seem to have done something wrong, but if I manually send it to the background then I can interact while it's recording that part of the screen.

**Comment by mephux** [comment] 2016-12-08 01:06
@phw had a chance to poke around, and it will take custom work to get it to work with i3 correctly (a lot I think). I'm assuming it will be custom for each tiling WM. 

Anyhow, will see if I can get a patch for i3 working at least.

**Comment by dmsmidt** [comment] 2016-12-09 09:17
@mephux a patch for i3 would be great.
But would be even better if it isn't tiling WM specific.

I use: gtk3 3.22.4-1 and i3-wm 4.13-1.

**Comment by mephux** [comment] 2017-01-09 20:38
@phw @ibrahima @dmsmidt I looked at this for a few days. No idea why it's now allowing it to pass through. I debugged everything I could think of. Super confused on this one. :-\

**Comment by mephux** [comment] 2017-01-09 20:44
to further elaborate compton is likely the problem but I couldn't pin it down.

**Comment by phw** [comment] 2017-01-12 07:50
@mephux Thanks a lot for this investigation, very much appreciated. But looks like there is not much I can do, if it needs probably be addressed in Gtk and/or i3

To be honest tiling window managers are not really the target for Peek. I am happy if it works there, but I probably won't invest time debugging and fixing it myself. I will accept patches, though :)

Closing this for now, feel free to reopen if there is some chance we can get this fixed here.

**Closed by phw** 2017-01-12 07:50 UTC
Labels: bug, upstream

**Comment by dmsmidt** [comment] 2017-01-12 09:31
@mephux thanks for your time, @phw a pitty we can't get this working. Could you mention the known limitations on the project page?

**Comment by phw** [comment] 2017-04-24 09:57
I was playing with i3 and sway a bit and also tried it there (actually quite like i3, even though tiling window managers are not my thing in general). Found out this was reported to i3 a few days back: https://github.com/i3/i3/issues/2742 . Fact is that i3 does not support the shape extension, and this was left out somewhat intentional as it is not a typical use case for tiling window managers. Maybe they will consider implementing this :)

On Sway it is a different story. There is some click through behavior, but the clicks are triggered completely off and moving & resizing the peek window is nearly impossible (the entire handling of floating windows seems to be buggy, but sway is work in progress anyway)

**Comment by phw** [comment] 2017-06-13 13:03
Also tracked for Awesome WM at https://github.com/awesomeWM/awesome/issues/1827

**Comment by pciavald** [comment] 2017-07-07 17:55
Would be interested in this feature too. Switching to another software for now, but i'll gladly come back if the thread is updated.

**Comment by erayaydin** [comment] 2017-08-11 08:08
I'm also interesting with this feature. For now, you can use `scratchpad`. Open `peek` and set location after starting peek, hide peek to scratchpad. When you finished recording you can get 'peek' from scratchpad. It will record :+1: 

But there should be a nice way for recording i3 window with peek.

**Comment by tmccombs** [comment] 2017-09-14 17:14
Peek is the best gif screen recorder I have found. I wish it worked better with i3.

**Comment by pachonk** [comment] 2017-11-12 15:59
So the way to do it is to make _both_ peek and the window you're trying to capture into "floating mode" (`$mod` + `shift` + `space` is default).
Put peek just above the window you want to capture and fire away...
It's a pain but better than nothing:
![image](https://user-images.githubusercontent.com/6721355/32700820-16fbae8a-c790-11e7-810a-7b361e05da68.png)

*NOTE: compton or equal must be running.*

**Comment by MattMcMurray** [comment] 2017-11-20 19:11
Furthering @pachonk's point: Stacked (`$mod+s`) and tabbed (`$mod+w`) mode also work

**Comment by pachonk** [comment] 2017-11-20 19:30
@MattMcMurray Nice tip, that's definitely easier than moving all the windows around like an ancient windowed WM

**Comment by nberrios** [comment] 2018-02-01 21:44
@pachonk yer a wizard

**Comment by pachonk** [comment] 2018-02-01 21:45
@nberrios Thanks, I had to do like 3 hours of research over something so small to finally find that... Lol

**Comment by AndreasBackx** [comment] 2018-07-30 10:44
Unfortunately if you want to record something like polybar, you cannot easily set it to floating mode.

**Comment by salmanulfarzy** [comment] 2019-08-27 11:29
https://github.com/i3/i3/pull/3514 might solve this.

**Comment by rassie** [comment] 2019-12-09 21:09
I can confirm that this is actually solved. i3 4.17.1, peek 1.4.0, no compton or scratchpad needed.

**Comment by 4khi1** [comment] 2020-01-23 18:24
> I can confirm that this is actually solved. i3 4.17.1, peek 1.4.0, no compton or scratchpad needed.

worked for me..... :+1:

**Comment by jc00ke** [comment] 2020-01-28 17:45
Same here, thank you!

**Comment by tdakhran** [comment] 2020-11-03 10:41
> I can confirm that this is actually solved. i3 4.17.1, peek 1.4.0, no compton or scratchpad needed.

Works!
