### ISSUE TITLE
Some RTL and translation issues in the About window

### ISSUE THREAD

**Issue by mohamedsakhri** [phw/peek#35] opened 2016-10-25 15:15 UTC
I've noticed some minor issues in the about window while using the Arabic version of peek.

- The window's title "about Peek" (in Arabic) isn't RTL
- The content in "credits" ( created by, translated by...) isn't covered in the translation file on transifix. There is some mistakes in the Arabic translation and there is no way to fix it.

![peek_004](https://cloud.githubusercontent.com/assets/2544216/19691955/6be07008-9ad6-11e6-9380-0f9406a7664a.png)

**Comment by phw** [comment] 2016-10-25 20:31
Most translations in this dialog are predefined by Gtk, if they need to be changed it must be done upstream. The files are at https://git.gnome.org/browse/gtk+/tree/po

Regarding the Window's title I am not sure what is happening, Peek does not explicitly set the direction. I will see if I can get my system configured for proper RTL layout so I can actually test it.

**Comment by mohamedsakhri** [comment] 2016-10-26 12:43
The Window's title should be "Peek عنْ". "عنْ" is "about" in Arabic, than followed by Peek, from right to left. As you can see in the screenshot, the order is flipped.

**Comment by phw** [comment] 2016-10-26 13:21
Probably also a Gtk issue. Can you say which desktop environment and which version of Gtk you are using?

Here are two results from my systems:

![peek-arabic-gnome-3 22-gtk-3 22](https://cloud.githubusercontent.com/assets/29852/19727153/87dc016a-9b8e-11e6-998b-29db0bf87dc7.png)
Peek on my Arch Linux box with Gnome 3.22 / Gtk 3.22 (this is using CSD, so does not have the issue in the title bar anyway)

![peek-arabic-ubuntu-16 04-unity-gtk-3 18](https://cloud.githubusercontent.com/assets/29852/19727319/350cf650-9b8f-11e6-88df-f38aa4017222.png)
Peek on Ubuntu 16.04 with Unity and Gtk 3.18

What's wrong on Unity is the alignment of the title, but the bilingual text looks fine. Also some spelling differences can be seen, the first screenshot should reflect the more or less current state of the translations in Gtk, does it fix the mistakes you see?

All in all I am probably going to close this, from the side of Peek everything seems to be ok and the issues encountered are either Gtk or desktop related.

**Comment by mohamedsakhri** [comment] 2016-10-26 13:33
I'm using Linux Mint 18 with XFCE as DE, GTK 3.18. I also tested on Cinnamon. Same result.

You are right. It's a GTK issue. I've just tested another program who has a similar about window and it has the same issue.

**Comment by phw** [comment] 2016-10-26 14:15
Ok, I'm closing this. I did a last test on Debian 8 also with Xfce and Gtk 3.14 where I cn reproduce it, but it is clearly a Gtk issue.

![peek-arabic-debian-8-xfce-4 10-gtk-3 14](https://cloud.githubusercontent.com/assets/29852/19729474/635f0d06-9b97-11e6-9c6f-13f042e4290b.png)

**Closed by phw** 2016-10-26 14:15 UTC
Labels: bug
