### ISSUE TITLE
Use byzanz libary

### ISSUE THREAD

**Issue by crantisz** [phw/peek#156] opened 2017-06-19 11:26 UTC
Byzanz is a gif recording libary, creates less size gif with better quality. Check this examples:

Peek (3.8MB): 
![peek 2017-06-19 09-39](https://user-images.githubusercontent.com/1749968/27282929-bd37df66-54fa-11e7-95d8-16fd13af9145.gif)

Byzanz(0.3MB)
![out](https://user-images.githubusercontent.com/1749968/27282950-d32bed58-54fa-11e7-895d-d050e3f2827e.gif)

So it will be great if Peek will record via Byzanz as option.

**Comment by phw** [comment] 2017-06-19 11:45
I had byzanz support on my original feature list, but I dropped it after I could not get the recording to work as I needed it. AFAIK byzanz actually does not expose a library (or at least none gets installed by default), and the command line tool `byzanz-record` expects you to set a duration in advance (defaults to 10 seconds). That's not really what I want and I found no way around this.

Regarding the quality: Which version of peek are you using and with which recording backend (peek will tell you if you start it, one of gnome-shell, ffmpeg or avconv)?

Because what I see above is likely mostly caused by video encoding artifacts in the source video recorded, and those get only worse when converted to GIF (as it increases the number of colors and makes an optimal palette more difficult, and also more changes per frame). Until 1.0.3 the gnome-shell backend used a lossy source video, and that would explain the bad results.

Just for a quick test I recorded part of that byzanz animation with Peek 1.0.3, the result is much smaller and better quality (you can't really compare it to your original recordings, though).

![peek 2017-06-19 13-36](https://user-images.githubusercontent.com/29852/27283529-07c6a662-54f5-11e7-9b18-f35fe73aa04c.gif)

**Comment by crantisz** [comment] 2017-06-19 11:55
Ok, I'm going to update Peek, now it 1.0.0 version

**Comment by crantisz** [comment] 2017-06-19 12:10
1.0.3 version records much smaller files! 0.4MB its very close to byzanz:
![peek 2017-06-19 14-58](https://user-images.githubusercontent.com/1749968/27284100-00d2ccfe-5500-11e7-8c5c-f9327f3731e8.gif)
byzanz still smaller, but colors not so accurate.. So, its great result

**Comment by phw** [comment] 2017-06-19 12:32
Cool, good to see that it turns out so much better. I am glad I got that fixed finally :)

Yes, still a bit larger. Byzanz actually does one nice thing: it has a dynamic delay between frames, whereas the files from Picard have a fixed delay. That means there is even a layer in the files if it is totally empty and unchanged from the first.

But when I look at the results the main difference seems to be that the file generated with Peek use some dithered colors, whereas Byzanz uses more flat colors. I think that explains both the larger file size of Peek and why Byzanz' colors are more off.

Anyway, I am going to close this, as I don't intent to implement byzanz support. It would need some patches to upstream byzanz to be usable for Peek.

**Closed by phw** 2017-06-19 12:32 UTC
Labels: enhancement
