### ISSUE TITLE
GIF processing cause serious lagging

### ISSUE THREAD

**Issue by ViBE-HU** [phw/peek#25] opened 2016-10-09 10:19 UTC
After recording the application cause lag and makes the system useless for minutes. I'm on Ubuntu 16.04 64 bit.

**Comment by lolilolicon** [comment] 2016-10-10 04:08
@phw perhaps consider capping `convert` resources, see [this comment](https://unix.stackexchange.com/questions/113695/gif-screencasting-the-unix-way/165147#165147), for example.

**Comment by phw** [comment] 2016-10-13 09:03
@lolilolicon Thanks for that, that could help. I cannot really reproduce the lagging here, but it could help :)

**Comment by lots0logs** [comment] 2016-10-26 03:51
I also experienced this. I'm using Arch. The severity of the issue depends on how much RAM is available on your system, the length of your recording, and how much activity you are recording (meaning how much of the screen has to be redrawn from one frame to the next because it changed). I have a memory monitor widget in my task bar and I can see that it quickly fills up all available memory for recordings longer than 15-20 seconds. The kernel then tries to flush whatever it can to swap but that doesnt prevent the system from stalling for a couple seconds. I think for a lower-end system it would stall for a lot longer (I have a core i7 with 12MB RAM). What sucks about the issue is that 2 out of 3 times you end up losing your recording because when the system stops lagging the file it saves is empty (0 bytes).

**Comment by lolilolicon** [comment] 2016-10-26 04:18
> I can see that it quickly fills up all available memory for recordings longer than 15-20 seconds

See issue #2

**Comment by lots0logs** [comment] 2016-10-26 04:24
@lolilolicon Yeah I can't believe I didn't realize that from the start! 

![homer-simpson-doh](https://cloud.githubusercontent.com/assets/4675662/19713252/1cb59b00-9b0a-11e6-9c75-9a1fa2eb36ed.gif)

**Comment by vangourd** [comment] 2016-11-23 17:21
I'm on Elementary OS Loki with it's Ubuntu 16.04 base on an Intel NUC6I3SYK. 

**Peek actually locks up my system so badly I have to reboot** (Cannot restart Xserver CTRL-ALT-BACKSPACE, cannot change to a terminal (CTRL + F1). I have to manage my memory well as this system doesn't have an abundance of it but I would love to see some better limits on how Peek uses resources. I'm assuming that's what is causing this problem for me. 

I can't seem to find any relevant logs on the issue in my journal, or in my Xserver logs. I attempted your TMP directory change recommendation but it opened Peek and I was unable to record anything after the fact. I'm assuming that might be a permissions problem so I will attempt to troubleshoot that later but I wanted to get a comment written as this software is pretty important to me building docs. 

Let me know if I can provide any more useful debugging info.

**Comment by lots0logs** [comment] 2016-11-23 21:02
@vangourd I started working on this in #37 but havent had time to finish it yet :grimacing:

**Comment by dandv** [comment] 2017-02-15 19:49
I've just noticed huge memory and CPU use with a longer recording (~30 seconds):

![image](https://cloud.githubusercontent.com/assets/33569/22992511/c2a4c168-f374-11e6-95e6-889137a0a944.png)

Another time when I had less RAM available, my Ubuntu 16.04 locked up and I had to just wait for a few minutes.

**Comment by phw** [comment] 2017-02-18 18:43
I think this should be fixed by fixing #2. Please reopen if this occurs even with the latest revision from git.

**Closed by phw** 2017-02-18 18:43 UTC
Labels: bug
