### ISSUE TITLE
Could not start recording, already an active recording using org.gnome.Shell.Screencast?

### ISSUE THREAD

**Issue by hcal** [phw/peek#325] opened 2018-05-31 22:14 UTC
Peek: 1.3.1
GTK: 3.22.26
GLib: 2.54.3

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

As far as I can tell there is no other screen recording active.   I get this error when recording an mpg, but not when recording a gif.  I'm on wayland if that matters.  Also, the program works well enough for me and I'm providing feed back because I thought it might help the project.  If not please close.

**Comment by AlexWayfer** [comment] 2018-06-04 15:44
Duplicate of #287, I think.

**Comment by phw** [comment] 2018-06-05 06:01
Thanks for reporting.

Yes. Please make sure you have gstreamer ugly plugins installed and also the H264 codec. If that does not solve your issue, have a look at the gnome shell output in journalctl.

**Closed by phw** 2018-06-05 06:01 UTC
Labels: duplicate

**Comment by RezaIr7200** [comment] 2019-07-28 07:13
I have same problem
Gnome log:
`gnome-shell[2783]: Ignoring excess values in shadow definition`
