### ISSUE TITLE
Recording error using Peek

### ISSUE THREAD

**Issue by ljvmiranda921** [phw/peek#352] opened 2018-08-24 00:56 UTC
Peek: 1.3.1
GTK: 3.18.9
GLib: 2.48.2

Details:
```
Command "ffmpeg -f x11grab -show_region 0 -framerate 10 -video_size 682x519 -i :0+576,819 -filter:v scale=iw/1:-1 -codec:v libvpx-vp9 -lossless 1 -r 10 -y /home/ljvm/.cache/peek/peek4U2RNZ.webm" failed with status 256 (received signal 0).

Output:
ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers  built with gcc 4.8.2 (GCC) 20140120 (Red Hat 4.8.2-15)  configuration: --prefix=/home/ljvm/anaconda3 --disable-doc --disable-openssl --enable-shared --enable-static --extra-cflags='-Wall -g -m64 -pipe -O3 -march=x86-64 -fPIC' --extra-cxxflags='-Wall -g -m64 -pipe -O3 -march=x86-64 -fPIC' --extra-libs='-lpthread -lm -lz' --enable-zlib --enable-pic --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --enable-libfreetype --enable-gnutls --enable-libx264 --enable-libopenh264  libavutil      56. 14.100 / 56. 14.100  libavcodec     58. 18.100 / 58. 18.100  libavformat    58. 12.100 / 58. 12.100  libavdevice    58.  3.100 / 58.  3.100  libavfilter     7. 16.100 /  7. 16.100  libavresample   4.  0.  0 /  4.  0.  0  libswscale      5.  1.100 /  5.  1.100  libswresample   3.  1.100 /  3.  1.100  libpostproc    55.  1.100 / 55.  1.100Unrecognized option 'show_region'.Error splitting the argument list: Option not found
```

**Comment by gort818** [comment] 2018-08-26 18:28
Check this #315

**Comment by phw** [comment] 2018-10-03 10:05
Closing as duplicate of #315, please compile ffmpeg with --enable-libxcb

**Closed by phw** 2018-10-03 10:05 UTC
