### ISSUE TITLE
problem feedback{1.0.0 + 1.0.1}

### ISSUE THREAD

**Issue by ghost** [phw/peek#106] opened 2017-03-15 19:12 UTC
Ubuntu 16.4»  
-registration problem » http://prnt.sc/ekbzh3
-didn't seem to register
-the problem is that conversion to GIF
-blurred mp4. the image is not clear.

**Comment by phw** [comment] 2017-03-15 21:36
The screenshot is from Peek 0.8 or earlier. Ease install the latest 1.0.0 and see if this fixes your issues.

What exactly do you mean by "didn't seem to register"?

**Comment by cmedya** [comment] 2017-03-16 08:31
-Yes.screenshot from the previous version
-1.0.0 I've installed
-does not save as an animated GIF
-the GIF does not appear in the saved location that you register

**Comment by phw** [comment] 2017-03-16 09:27
Can you please run Peek from command line, record and save a GIF and post the complete output here?

Also please tell me which version of Ubuntu you use and what the output of `convert -version` is.

**Comment by cmedya** [comment] 2017-03-16 15:12
-Version: Ubuntu 16.4
-`Version: ImageMagick 6.8.9-9 Q16 x86_64 2017-03-14 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib`

**Comment by phw** [comment] 2017-03-16 15:52
Thanks, this setup should work. But I really need the output from peek. Please open a terminal and run:

    G_MESSAGES_DEBUG=all peek

Then record a GIF and save it and post the output here.

**Comment by cmedya** [comment] 2017-03-17 08:32
(peek:4239): Gtk-DEBUG: Connecting to session manager
** (peek:4239): DEBUG: desktop-integration.vala:133: Desktop: Unity
** (peek:4239): DEBUG: application.vala:303: Decoration layout: menu:minimize,maximize,close
** (peek:4239): DEBUG: desktop-integration.vala:133: Desktop: Unity
** (peek:4239): DEBUG: application.vala:43: Loading local settings failed: Failed to open file './data/gschemas.compiled': open() failed: Böyle bir dosya ya da dizin yok
** (peek:4239): DEBUG: application.vala:196: Changed keybinding_toggle_recording  => <Ctrl><Alt>R

** (peek:4239): DEBUG: desktop-integration.vala:133: Desktop: Unity
** (peek:4239): DEBUG: utils.vala:68: Looking for executable ffmpeg (0): /usr/bin/ffmpeg

Using screen recorder backend ffmpeg
** (peek:4239): DEBUG: desktop-integration.vala:133: Desktop: Unity
** (peek:4239): DEBUG: recording-area.vala:38: Absolute recording area x: 614, y: 296, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:45: Screen w: 1440, h: 900
** (peek:4239): DEBUG: recording-area.vala:58: Clipped recording area x: 614, y: 296, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:69: Scaled recording area x: 614, y: 296, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:38: Absolute recording area x: 614, y: 296, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:45: Screen w: 1440, h: 900
** (peek:4239): DEBUG: recording-area.vala:58: Clipped recording area x: 614, y: 296, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:69: Scaled recording area x: 614, y: 296, w: 421, h: 275
** (peek:4239): DEBUG: application-window.vala:415: freeze_window_size w: 423, h: 313
** (peek:4239): DEBUG: recording-area.vala:38: Absolute recording area x: 849, y: 285, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:45: Screen w: 1440, h: 900
** (peek:4239): DEBUG: recording-area.vala:58: Clipped recording area x: 849, y: 285, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:69: Scaled recording area x: 849, y: 285, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:38: Absolute recording area x: 849, y: 285, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:45: Screen w: 1440, h: 900
** (peek:4239): DEBUG: recording-area.vala:58: Clipped recording area x: 849, y: 285, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:69: Scaled recording area x: 849, y: 285, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:38: Absolute recording area x: 849, y: 285, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:45: Screen w: 1440, h: 900
** (peek:4239): DEBUG: recording-area.vala:58: Clipped recording area x: 849, y: 285, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:69: Scaled recording area x: 849, y: 285, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:38: Absolute recording area x: 849, y: 285, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:45: Screen w: 1440, h: 900
** (peek:4239): DEBUG: recording-area.vala:58: Clipped recording area x: 849, y: 285, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:69: Scaled recording area x: 849, y: 285, w: 421, h: 275
** (peek:4239): DEBUG: application-window.vala:333: Recording area: 849, 285, 421, 275

** (peek:4239): DEBUG: utils.vala:23: Cache directory does already exist /home/up7/.cache/peek

** (peek:4239): DEBUG: utils.vala:38: Temp file: /home/up7/.cache/peek/peek1ST4WY.pam

** (peek:4239): DEBUG: recording-area.vala:38: Absolute recording area x: 849, y: 285, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:45: Screen w: 1440, h: 900
** (peek:4239): DEBUG: recording-area.vala:58: Clipped recording area x: 849, y: 285, w: 421, h: 275
** (peek:4239): DEBUG: recording-area.vala:69: Scaled recording area x: 849, y: 285, w: 421, h: 275
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv --enable-version3 --disable-doc --disable-programs --disable-avdevice --disable-avfilter --disable-avformat --disable-avresample --disable-postproc --disable-swscale --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libvo_aacenc --enable-libvo_amrwbenc
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, x11grab, from ':0+849,285':
  Duration: N/A, start: 1489739408.335988, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 421x275, 12 fps, 12 tbr, 1000k tbn, 12 tbc
Output #0, rawvideo, to '/home/up7/.cache/peek/peek1ST4WY.pam':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: pam, rgb24, 210x137, q=2-31, 200 kb/s, 12 fps, 12 tbn, 12 tbc
    Metadata:
      encoder         : Lavc56.60.100 pam
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> pam (native))
Press [q] to stop, [?] for help
[swscaler @ 0x2092b60] Warning: data is not aligned! This can lead to a speedloss
** (peek:4239): DEBUG: base-screen-recorder.vala:39: Recording stopped91.8kbits/s    
frame=   65 fps= 12 q=-0.0 Lsize=    5483kB time=00:00:05.41 bitrate=8291.8kbits/s    
video:5483kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
** (peek:4239): DEBUG: command-line-screen-recorder.vala:29: Recorder process closed
** (peek:4239): DEBUG: command-line-screen-recorder.vala:33: recording process exited, term_sig: 0, exit_status: 0, success: true
** (peek:4239): DEBUG: Temporary file /home/up7/.cache/peek/peek1ST4WY.pam, 5614245 bytes
** (peek:4239): DEBUG: base-screen-recorder.vala:46: Started post processing
** (peek:4239): DEBUG: utils.vala:23: Cache directory does already exist /home/up7/.cache/peek

** (peek:4239): DEBUG: utils.vala:38: Temp file: /home/up7/.cache/peek/peekJG6SWY.gif

** (peek:4239): DEBUG: imagemagick-post-processor.vala:36: Running ImageMagick convert, saving to /home/up7/.cache/peek/peekJG6SWY.gif
** (peek:4239): DEBUG: utils.vala:23: Cache directory does already exist /home/up7/.cache/peek

** (peek:4239): DEBUG: application-window.vala:479: Showing file chooser
convert: NegativeOrZeroImageSize `/home/up7/.cache/peek/peek1ST4WY.pam' @ error/pnm.c/ReadPNMImage/415.
convert: no images defined `/home/up7/.cache/peek/peekJG6SWY.gif' @ error/convert.c/ConvertImageCommand/3210.
Error: Child process exited with code 1
** (peek:4239): DEBUG: base-screen-recorder.vala:49: Finished post processing
File save error: Error when getting information for file '/home/up7/.cache/peek/peekJG6SWY.gif': Böyle bir dosya ya da dizin yok
** (peek:4239): DEBUG: application-window.vala:359: Deleting temp file file:///home/up7/.cache/peek/peekJG6SWY.gif

** (peek:4239): DEBUG: application-window.vala:423: unfreeze_window_size w: 423, h: 313
Temp file delete error: Error removing file: Böyle bir dosya ya da dizin yok

**Comment by phw** [comment] 2017-03-17 19:18
This is very very strange.  ffmpeg records the video, and it also is not empty (roughly 5 MB in size). But ImageMagick cannot decode it. I will try to reproduce this on Ubuntu 16.04. If I send you a test file could you try converting this with convert?

**Comment by cmedya** [comment] 2017-03-23 07:49
Yes. let's test it.

**Comment by cmedya** [comment] 2017-03-29 07:39
Peek 1.0.1
------------
.......... ~ $ G_MESSAGES_DEBUG=all peek

(peek:4200): Gtk-WARNING **: Theme parsing error: xfce.css:17:22: Not a valid image
(peek:4200): Gtk-DEBUG: Connecting to session manager
** (peek:4200): DEBUG: desktop-integration.vala:140: Desktop: X-Cinnamon
** (peek:4200): DEBUG: application.vala:303: Decoration layout: menu:minimize,maximize,close
** (peek:4200): DEBUG: desktop-integration.vala:140: Desktop: X-Cinnamon
** (peek:4200): DEBUG: application.vala:43: Loading local settings failed: Failed to open file './data/gschemas.compiled': open() failed: Böyle bir dosya ya da dizin yok
** (peek:4200): DEBUG: application.vala:196: Changed keybinding_toggle_recording  => <Ctrl><Alt>R

** (peek:4200): DEBUG: desktop-integration.vala:140: Desktop: X-Cinnamon
** (peek:4200): DEBUG: utils.vala:68: Looking for executable ffmpeg (0): /usr/bin/ffmpeg

Using screen recorder backend ffmpeg

(peek:4200): Gtk-WARNING **: Theme parsing error: xfce.css:17:22: Not a valid image
** (peek:4200): DEBUG: desktop-integration.vala:140: Desktop: X-Cinnamon
** (peek:4200): DEBUG: recording-area.vala:38: Absolute recording area x: 492, y: 346, w: 456, h: 229
** (peek:4200): DEBUG: recording-area.vala:45: Screen w: 1440, h: 900
** (peek:4200): DEBUG: recording-area.vala:58: Clipped recording area x: 492, y: 346, w: 456, h: 229
** (peek:4200): DEBUG: recording-area.vala:69: Scaled recording area x: 492, y: 346, w: 456, h: 229
** (peek:4200): DEBUG: recording-area.vala:38: Absolute recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: recording-area.vala:45: Screen w: 1440, h: 900
** (peek:4200): DEBUG: recording-area.vala:58: Clipped recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: recording-area.vala:69: Scaled recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: application-window.vala:410: freeze_window_size w: 500, h: 300
** (peek:4200): DEBUG: recording-area.vala:38: Absolute recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: recording-area.vala:45: Screen w: 1440, h: 900
** (peek:4200): DEBUG: recording-area.vala:58: Clipped recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: recording-area.vala:69: Scaled recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: recording-area.vala:38: Absolute recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: recording-area.vala:45: Screen w: 1440, h: 900
** (peek:4200): DEBUG: recording-area.vala:58: Clipped recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: recording-area.vala:69: Scaled recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: recording-area.vala:38: Absolute recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: recording-area.vala:45: Screen w: 1440, h: 900
** (peek:4200): DEBUG: recording-area.vala:58: Clipped recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: recording-area.vala:69: Scaled recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: recording-area.vala:38: Absolute recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: recording-area.vala:45: Screen w: 1440, h: 900
** (peek:4200): DEBUG: recording-area.vala:58: Clipped recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: recording-area.vala:69: Scaled recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: application-window.vala:328: Recording area: 492, 356, 456, 219

** (peek:4200): DEBUG: utils.vala:23: Cache directory does already exist /home/.../.cache/peek

** (peek:4200): DEBUG: utils.vala:38: Temp file: /home/.../.cache/peek/peekHBFUXY.pam

** (peek:4200): DEBUG: recording-area.vala:38: Absolute recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: recording-area.vala:45: Screen w: 1440, h: 900
** (peek:4200): DEBUG: recording-area.vala:58: Clipped recording area x: 492, y: 356, w: 456, h: 219
** (peek:4200): DEBUG: recording-area.vala:69: Scaled recording area x: 492, y: 356, w: 456, h: 219
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv --enable-version3 --disable-doc --disable-programs --disable-avdevice --disable-avfilter --disable-avformat --disable-avresample --disable-postproc --disable-swscale --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libvo_aacenc --enable-libvo_amrwbenc
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, x11grab, from ':0+492,356':
  Duration: N/A, start: 1490772887.122198, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 456x219, 15 fps, 15 tbr, 1000k tbn, 15 tbc
Output #0, rawvideo, to '/home/.../.cache/peek/peekHBFUXY.pam':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: pam, rgb24, 228x109, q=2-31, 200 kb/s, 15 fps, 15 tbn, 15 tbc
    Metadata:
      encoder         : Lavc56.60.100 pam
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> pam (native))
Press [q] to stop, [?] for help
frame=   10 fps=0.0 q=-0.0 size=     729kB time=00:00:00.66 bitrate=8954.3kbits/frame=   18 fps= 17 q=-0.0 size=    1312kB time=00:00:01.20 bitrate=8954.3kbits/frame=   26 fps= 16 q=-0.0 size=    1895kB time=00:00:01.73 bitrate=8954.3kbits/frame=   34 fps= 16 q=-0.0 size=    2478kB time=00:00:02.26 bitrate=8954.3kbits/frame=   42 fps= 16 q=-0.0 size=    3061kB time=00:00:02.80 bitrate=8954.3kbits/frame=   50 fps= 16 q=-0.0 size=    3644kB time=00:00:03.33 bitrate=8954.3kbits/frame=   58 fps= 16 q=-0.0 size=    4226kB time=00:00:03.86 bitrate=8954.3kbits/frame=   66 fps= 15 q=-0.0 size=    4809kB time=00:00:04.40 bitrate=8954.3kbits/** (peek:4200): DEBUG: base-screen-recorder.vala:39: Recording stopped
frame=   67 fps= 15 q=-0.0 Lsize=    4882kB time=00:00:04.46 bitrate=8954.3kbits/s    
video:4882kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
** (peek:4200): DEBUG: command-line-screen-recorder.vala:29: Recorder process closed
** (peek:4200): DEBUG: command-line-screen-recorder.vala:33: recording process exited, term_sig: 0, exit_status: 0, success: true
** (peek:4200): DEBUG: Temporary file /home/.../.cache/peek/peekHBFUXY.pam, 4999473 bytes
** (peek:4200): DEBUG: base-screen-recorder.vala:46: Started post processing
** (peek:4200): DEBUG: utils.vala:23: Cache directory does already exist /home/.../.cache/peek

** (peek:4200): DEBUG: utils.vala:38: Temp file: /home/.../.cache/peek/peekGYFJXY.gif

** (peek:4200): DEBUG: utils.vala:23: Cache directory does already exist /home/.../.cache/peek

** (peek:4200): DEBUG: imagemagick-post-processor.vala:34: Running ImageMagick convert, saving to /home/.../.cache/peek/peekGYFJXY.gif, using temporary path /home/.../.cache/peek
convert: NegativeOrZeroImageSize `/home/.../.cache/peek/peekHBFUXY.pam' @ error/pnm.c/ReadPNMImage/415.
convert: no images defined `/home/.../.cache/peek/peekGYFJXY.gif' @ error/convert.c/ConvertImageCommand/3210.
** (peek:4200): DEBUG: application-window.vala:474: Showing file chooser
Error: Child process exited with code 1
** (peek:4200): DEBUG: base-screen-recorder.vala:49: Finished post processing
** (peek:4200): DEBUG: application-window.vala:476: Selected file file:///home/.../Videolar/Peek%202017-03-29%2010-34.gif
File save error: Error when getting information for file '/home/.../.cache/peek/peekGYFJXY.gif': Böyle bir dosya ya da dizin yok
** (peek:4200): DEBUG: application-window.vala:354: Deleting temp file file:///home/.../.cache/peek/peekGYFJXY.gif

** (peek:4200): DEBUG: application-window.vala:418: unfreeze_window_size w: 500, h: 300
Temp file delete error: Error removing file: Böyle bir dosya ya da dizin yok

**Comment by johannesE** [comment] 2017-09-04 11:41
I am pretty sure that I have the same problem. The gif is just not saved. No error message or anything.

**Comment by phw** [comment] 2017-09-13 08:31
@johannesE It is actually more likely you encounter https://github.com/phw/peek/issues/112 , please have a look at that issues and the workarounds presented here.

**Comment by johannesE** [comment] 2017-09-13 08:40
@phw That is possible, even though I don't see any resource spikes during the render phase. What I found out yesterday is that gifs are not made for large images and if I set the `resolution downsampling` on my 4k display to at least 2, everything works as expected. Thank god, because there is no good alternative to peek. The simplicity is outstanding and I'm grateful for the work you put into it.

I would still appreciate it if you could show me any kind of error message when I try to create a gif and something fails.

**Comment by phw** [comment] 2017-09-13 08:52
> I would still appreciate it if you could show me any kind of error message when I try to create a gif and something fails.

Definitely Peek must have this :) Hope I can work on it again soon.

**Comment by phw** [comment] 2017-11-16 17:32
I am going to close this issue. As the recording was significantly refactored for the upcoming 1.2 release I think this should be fixed. Please try out the latest development version. If you still encounter problems with recording feel free to open a new issue.

**Closed by phw** 2017-11-16 17:32 UTC
Labels: need more info

**Comment by johannesE** [comment] 2017-11-16 18:12
Great, thanks!
