### ISSUE TITLE
now working report

### ISSUE THREAD

**Issue by roy-repo** [phw/peek#477] opened 2019-08-13 22:24 UTC
Peek: 1.3.1
GTK: 3.18.9
GLib: 2.48.2

Details:
```
Command "ffmpeg -f x11grab -show_region 0 -framerate 15 -video_size 1994x1119 -draw_mouse 0 -i :0+1327,462 -filter:v scale=iw/2:-1 -codec:v libvpx-vp9 -lossless 1 -r 15 -y /home/lyft/.cache/peek/peekYG9S6Z.webm" failed with status 256 (received signal 0).

Output:
ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1)  configuration: --prefix=/home/edwards/Downloads/FFmpeg-release-4.1/build --enable-pic --enable-shared --enable-cuda --enable-hardcoded-tables --extra-cflags=' -march=native '  libavutil      56. 22.100 / 56. 22.100  libavcodec     58. 35.100 / 58. 35.100  libavformat    58. 20.100 / 58. 20.100  libavdevice    58.  5.100 / 58.  5.100  libavfilter     7. 40.101 /  7. 40.101  libswscale      5.  3.100 /  5.  3.100  libswresample   3.  3.100 /  3.  3.100Unrecognized option 'lossless'.Error splitting the argument list: Option not found
```

**Comment by phw** [comment] 2019-09-24 10:18
Duplicate of #429

**Closed by phw** 2019-09-24 10:18 UTC
