### ISSUE TITLE
Ubuntu 16: unexpected error while recording, aborted

### ISSUE THREAD

**Issue by hkashyap** [phw/peek#381] opened 2018-10-15 19:20 UTC
I have tried to record in mp4, gif, webm, and apng. The record always fails in the beginning and gives me this following error.

Command "ffmpeg -f x11grab -show_region 0 -framerate 10 -video_size 1126x845 -i :0+391,147 -filter:v scale=iw/1:-1 -codec:v libvpx-vp9 -lossless 1 -r 10 -y /home/hk/.cache/peek/peek90EDRZ.webm" failed with status 256 (received signal 0).

Output:
ffmpeg version 4.0 Copyright (c) 2000-2018 the FFmpeg developers  built with gcc 7.2.0 (crosstool-NG fa8859cb)  configuration: --prefix=/home/hk/anaconda3 --cc=/tmp/build/80754af9/ffmpeg_1526323631431/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc --disable-doc --enable-shared --enable-static --enable-zlib --enable-pic --enable-gpl --enable-version3 --disable-nonfree --enable-hardcoded-tables --enable-avresample --enable-libfreetype --disable-openssl --disable-gnutls --enable-libvpx --enable-pthreads --enable-libopus --enable-postproc --disable-libx264  libavutil      56. 14.100 / 56. 14.100  libavcodec     58. 18.100 / 58. 18.100  libavformat    58. 12.100 / 58. 12.100  libavdevice    58.  3.100 / 58.  3.100  libavfilter     7. 16.100 /  7. 16.100  libavresample   4.  0.  0 /  4.  0.  0  libswscale      5.  1.100 /  5.  1.100  libswresample   3.  1.100 /  3.  1.100  libpostproc    55.  1.100 / 55.  1.100Unrecognized option 'show_region'.Error splitting the argument list: Option not found

**Comment by joshuayuan** [comment] 2018-11-08 00:17
Just installed peek, and get a similar error.

> Command "ffmpeg -f x11grab -show_region 0 -framerate 10 -video_size 1082x625 -i :0+123,164 -filter:v scale=iw/1:-1, crop=iw-mod(iw\,2):ih-mod(ih\,2) -codec:v libx264 -preset:v fast -profile:v baseline -pix_fmt yuv420p -r 10 -y /home/aaron/.cache/peek/peekBIG9RZ.mp4" failed with status 256 (received signal 0).
> 
> Output:
> ffmpeg version 3.4 Copyright (c) 2000-2017 the FFmpeg developers  built with gcc 7.2.0 (crosstool-NG 8a21ab48)  configuration: --prefix=/home/aaron/anaconda3 --disable-doc --enable-shared --extra-cflags='-fPIC -I/home/aaron/anaconda3/include' --extra-cxxflags='=-fPIC' --extra-libs='-L/home/aaron/anaconda3/lib -lz' --enable-pic --disable-static --disable-gpl --disable-nonfree --disable-openssl --enable-libvpx --cc=/home/aaron/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc --cxx=/home/aaron/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ --enable-libopus  libavutil      55. 78.100 / 55. 78.100  libavcodec     57.107.100 / 57.107.100  libavformat    57. 83.100 / 57. 83.100  libavdevice    57. 10.100 / 57. 10.100  libavfilter     6.107.100 /  6.107.100  libswscale      4.  8.100 /  4.  8.100  libswresample   2.  9.100 /  2.  9.100Unrecognized option 'show_region'.Error splitting the argument list: Option not found

**Comment by gort818** [comment] 2018-11-08 00:46
check this issue #315

**Comment by phw** [comment] 2019-09-24 10:17
Duplicate of #315

**Closed by phw** 2019-09-24 10:17 UTC
