### ISSUE TITLE
Maximise Peek Problem

### ISSUE THREAD

**Issue by orschiro** [phw/peek#74] opened 2017-02-02 10:04 UTC
Dear all, 

Can we fix the following maximise Peek problem?

![peek](https://cloud.githubusercontent.com/assets/170947/22544993/5216152e-e937-11e6-9c69-77bf4d216add.gif)

**Comment by phw** [comment] 2017-02-18 18:47
It took me a while to see the issue, but does the Peek window in this case automatically unmaximize? Very strange, cannot reproduce. I will try if I can reproduce on Ubuntu Unity.

**Comment by MariusQuabeck** [comment] 2017-02-18 23:58
I can reproduce the issue on Ubuntu 16.10 (unity)

**Comment by orschiro** [comment] 2017-02-19 07:41
Any ideas what is causing this behaviour on Ubuntu 16.10 Unity?

**Comment by phw** [comment] 2017-02-20 15:32
I an reproduce on Ubuntu 16.04 with Unity. Had not the time to do any serious debugging yet, and also not sure what causes it so far :( Will keep you updated.

**Comment by orschiro** [comment] 2017-02-20 19:00
Thank you, Philipp!

Let me know if I can provide you with any further information.

**Comment by phw** [comment] 2017-02-23 14:27
I have a suspicion: Once the recording starts I try to freeze the window size, so you cannot accidentally resize your window. I suspect this goes wrong in the full screen case on Unity. Have to check whether I can detect this and workaround it.

**Comment by orschiro** [comment] 2017-02-23 14:31
Maybe it has something to do with Unity's topbar?

**Comment by phw** [comment] 2017-02-24 08:37
I think I found a fix for this, at least I cannot reproduce it anymore. Would be great if you could test with the daily PPA

**Closed** 2017-02-24 08:36 UTC
Labels: bug

**Comment by orschiro** [comment] 2017-02-24 08:48
Wow, great!

This one?

sudo add-apt-repository ppa:peek-developers/daily

**Comment by phw** [comment] 2017-02-24 08:52
Exactly that. It is currently still building the new packages, so give it a few minutes. You can see the current status on  https://code.launchpad.net/~peek-developers/+recipe/peek-daily

**Comment by orschiro** [comment] 2017-02-24 10:48
Great, it seems to work with the new version. 

Thank you so much! :-)

**Comment by phw** [comment] 2017-02-24 10:49
You are welcome, I am glad this is fixed
