### ISSUE TITLE
stuck on rendering...

### ISSUE THREAD

**Issue by atar-axis** [phw/peek#279] opened 2018-02-15 13:36 UTC
I am on Antergos (based on Arch).
When installing the latest version from pacman, then `peek` got stuck on *rendering...*
There never appears an *Save to* dialogue, but the .cache files (`.mkv`) are created!

This does only happen at the pacman-Version!
It does work without any problem if i use the AppImage-Version or if I build it myself.

Therefore, as a temporary **workaround**, i replaced `/usr/bin/peek` by the one i compiled on my system.

This is the Debug-Log:

pacman:
```
env G_MESSAGES_DEBUG=all peek
(peek:14729): Gtk-DEBUG: Connecting to session manager
(peek:14729): Gtk-DEBUG: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(peek:14729): Gtk-DEBUG: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
(peek:14729): Gtk-DEBUG: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
** (peek:14729): DEBUG: desktop-integration.vala:168: Desktop: KDE
** (peek:14729): DEBUG: application.vala:286: GTK theme: Breeze
** (peek:14729): DEBUG: desktop-integration.vala:168: Desktop: KDE
** (peek:14729): DEBUG: application.vala:341: Decoration layout: menu:minimize,maximize,close
** (peek:14729): DEBUG: desktop-integration.vala:168: Desktop: KDE
** (peek:14729): DEBUG: application.vala:42: Loading local settings failed: Datei »./data/gschemas.compiled« konnte nicht geöffnet werden: open() ist gescheitert: Datei oder Verzeichnis nicht gefunden
** (peek:14729): DEBUG: application.vala:221: Changed keybinding_toggle_recording  => <Ctrl><Alt>R


** (peek:14729): WARNING **: Binding '<Ctrl><Alt>R' failed!
** (peek:14729): DEBUG: desktop-integration.vala:168: Desktop: KDE
** (peek:14729): DEBUG: utils.vala:68: Looking for executable ffmpeg (0): /usr/bin/ffmpeg

Using screen recorder backend ffmpeg

(peek:14729): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(peek:14729): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(peek:14729): Gtk-WARNING **: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(peek:14729): Gtk-WARNING **: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version
** (peek:14729): DEBUG: application-window.vala:824: Decoration layout: menu:minimize,maximize,close
** (peek:14729): DEBUG: recording-area.vala:38: Absolute recording area x: 577, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:14729): DEBUG: recording-area.vala:58: Clipped recording area x: 577, y: 225, w: 789, h: 476
** (peek:14729): DEBUG: recording-area.vala:69: Scaled recording area x: 577, y: 225, w: 789, h: 476
** (peek:14729): DEBUG: recording-area.vala:38: Absolute recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:14729): DEBUG: recording-area.vala:58: Clipped recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:69: Scaled recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: application-window.vala:587: freeze_window_size w: 817, h: 515
** (peek:14729): DEBUG: recording-area.vala:38: Absolute recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:14729): DEBUG: recording-area.vala:58: Clipped recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:69: Scaled recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:38: Absolute recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:14729): DEBUG: recording-area.vala:58: Clipped recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:69: Scaled recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:38: Absolute recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:14729): DEBUG: recording-area.vala:58: Clipped recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:69: Scaled recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:38: Absolute recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:14729): DEBUG: recording-area.vala:58: Clipped recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:69: Scaled recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: application-window.vala:468: Recording area: 550, 225, 815, 476

** (peek:14729): DEBUG: utils.vala:23: Cache directory does already exist /home/flood/.cache/peek

** (peek:14729): DEBUG: utils.vala:38: Temp file: /home/flood/.cache/peek/peekLGAFEZ.mkv

** (peek:14729): DEBUG: recording-area.vala:38: Absolute recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:14729): DEBUG: recording-area.vala:58: Clipped recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: recording-area.vala:69: Scaled recording area x: 550, y: 225, w: 815, h: 476
** (peek:14729): DEBUG: base-screen-recorder.vala:55: Recording stopped
```

build myself:
```
env G_MESSAGES_DEBUG=all ./peek
(peek:21931): Gtk-DEBUG: Connecting to session manager
(peek:21931): Gtk-DEBUG: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(peek:21931): Gtk-DEBUG: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
(peek:21931): Gtk-DEBUG: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
** (peek:21931): DEBUG: desktop-integration.vala:168: Desktop: KDE
** (peek:21931): DEBUG: application.vala:286: GTK theme: Breeze
** (peek:21931): DEBUG: desktop-integration.vala:168: Desktop: KDE
** (peek:21931): DEBUG: application.vala:341: Decoration layout: menu:minimize,maximize,close
** (peek:21931): DEBUG: desktop-integration.vala:168: Desktop: KDE
** (peek:21931): DEBUG: application.vala:221: Changed keybinding_toggle_recording  => <Ctrl><Alt>R


** (peek:21931): WARNING **: Binding '<Ctrl><Alt>R' failed!
** (peek:21931): DEBUG: desktop-integration.vala:168: Desktop: KDE
** (peek:21931): DEBUG: utils.vala:68: Looking for executable ffmpeg (0): /usr/bin/ffmpeg

Using screen recorder backend ffmpeg

(peek:21931): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(peek:21931): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(peek:21931): Gtk-WARNING **: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(peek:21931): Gtk-WARNING **: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version
** (peek:21931): DEBUG: application-window.vala:824: Decoration layout: menu:minimize,maximize,close
** (peek:21931): DEBUG: recording-area.vala:38: Absolute recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:21931): DEBUG: recording-area.vala:58: Clipped recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:69: Scaled recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:38: Absolute recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:21931): DEBUG: recording-area.vala:58: Clipped recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:69: Scaled recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: application-window.vala:587: freeze_window_size w: 817, h: 515
** (peek:21931): DEBUG: recording-area.vala:38: Absolute recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:21931): DEBUG: recording-area.vala:58: Clipped recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:69: Scaled recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:38: Absolute recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:21931): DEBUG: recording-area.vala:58: Clipped recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:69: Scaled recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:38: Absolute recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:21931): DEBUG: recording-area.vala:58: Clipped recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:69: Scaled recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:38: Absolute recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:21931): DEBUG: recording-area.vala:58: Clipped recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:69: Scaled recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: application-window.vala:468: Recording area: 457, 115, 815, 476

** (peek:21931): DEBUG: utils.vala:23: Cache directory does already exist /home/flood/.cache/peek

** (peek:21931): DEBUG: utils.vala:38: Temp file: /home/flood/.cache/peek/peekPN9EEZ.mkv

** (peek:21931): DEBUG: recording-area.vala:38: Absolute recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:45: Screen w: 1366, h: 768
** (peek:21931): DEBUG: recording-area.vala:58: Clipped recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: recording-area.vala:69: Scaled recording area x: 457, y: 115, w: 815, h: 476
** (peek:21931): DEBUG: base-screen-recorder.vala:55: Recording stopped
** (peek:21931): DEBUG: cli-screen-recorder.vala:34: recording process exited, term_sig: 0, exit_status: 0, success: true
** (peek:21931): DEBUG: Temporary file /home/flood/.cache/peek/peekPN9EEZ.mkv, 282087 bytes
** (peek:21931): DEBUG: base-screen-recorder.vala:67: Started post processing
** (peek:21931): DEBUG: utils.vala:68: Looking for executable ffmpeg (0): /usr/bin/ffmpeg

** (peek:21931): DEBUG: post-processing-pipeline.vala:30: Running post processor PeekPostProcessingFfmpegPostProcessor with files 1
** (peek:21931): DEBUG: utils.vala:23: Cache directory does already exist /home/flood/.cache/peek

** (peek:21931): DEBUG: utils.vala:38: Temp file: /home/flood/.cache/peek/peekECYCEZ.png

** (peek:21931): DEBUG: application-window.vala:637: Showing file chooser (GtkFileChooserDialog)
** (peek:21931): DEBUG: utils.vala:23: Cache directory does already exist /home/flood/.cache/peek

** (peek:21931): DEBUG: utils.vala:38: Temp file: /home/flood/.cache/peek/peekJDWKEZ.gif

** (peek:21931): DEBUG: base-screen-recorder.vala:70: Finished post processing
** (peek:21931): DEBUG: application-window.vala:639: Selected file file:///home/flood/Videos/Peek%202018-02-15%2014-43.gif
** (peek:21931): DEBUG: application-window.vala:666: File saved true: file:///home/flood/Videos/Peek%202018-02-15%2014-43.gif
** (peek:21931): DEBUG: desktop-integration.vala:168: Desktop: KDE
** (peek:21931): DEBUG: desktop-integration.vala:168: Desktop: KDE
** (peek:21931): DEBUG: desktop-integration.vala:168: Desktop: KDE
** (peek:21931): DEBUG: application-window.vala:734: Showing desktop notification: Animation als “Peek 2018-02-15 14-43.gif” gespeichert
** (peek:21931): DEBUG: application-window.vala:595: unfreeze_window_size w: 817, h: 515
** (peek:21931): DEBUG: application-window.vala:513: Deleting temp file file:///home/flood/.cache/peek/peekJDWKEZ.gif

** (peek:21931): DEBUG: application-window.vala:517: Temp file deleted: true
```

**Comment by phw** [comment] 2018-02-15 14:15
This is likely the same as #274, but you gave me an idea. Can you test the latest from AUR?

What I disabled again was the use of GtkFileChooserNative. It is working well for me on my GNOME, but maybe I have to test with other DEs.

**Comment by phw** [comment] 2018-02-15 14:36
Closing as duplicate of #274

**Closed** 2018-02-15 22:31 UTC
Labels: bug, packaging
