### ISSUE TITLE
The saved dialog makes it seem like something went wrong

### ISSUE THREAD

**Issue by elevine** [phw/peek#62] opened 2017-01-11 22:12 UTC
Peek is a great tool!  However, every time I create a GIF and see the saved dialog with the red exclamation mark, it makes me thing that something went wrong.  

![screenshot from 2017-01-11 16-25-33](https://cloud.githubusercontent.com/assets/391059/21868461/ca0a2566-d820-11e6-8813-11a7238049d3.png)

Ideally, the icon would be something more positive like a green checkmark.

**Comment by phw** [comment] 2017-01-11 22:38
Duplicate of #55

That's actually not a dialog created by Peek directly but the way the desktop notification is presented to you by the desktop environment. You are using Unity, too, right?

**Closed by phw** 2017-01-11 22:38 UTC

**Comment by elevine** [comment] 2017-01-12 17:39
Yep I'm using Ubuntu with Unity.  Thanks for the quick response!
