### ISSUE TITLE
Could not start recording in MP4

### ISSUE THREAD

**Issue by silvafabio** [phw/peek#425] opened 2019-03-12 00:45 UTC
Peek: 1.3.1
GTK: 3.24.2
GLib: 2.58.1

Details:
```
Could not start recording, already an active recording using org.gnome.Shell.Screencast?
```

**Comment by phw** [comment] 2019-03-15 10:15
This is likely a duplicate of #287, please refer to the answers there. Usually this is fixed by installing gstreamer ugly plugins

**Closed by phw** 2019-03-15 10:15 UTC
