### ISSUE TITLE
System hung, GIF failed to save

### ISSUE THREAD

**Issue by meetdilip** [phw/peek#132] opened 2017-04-21 06:21 UTC
After one recording process, the 16.04 got hung. PC was barely responsive. I had to use the power button to shutdown. When checked the " Videos " folder, there was no sign of GIF even though I went through the process of naming it and saving under " Videos " before it hung.

**Comment by phw** [comment] 2017-04-21 08:18
This pretty sure was you system starting to swap. The RAM usage of imagemagick can become enormous. ImageMagick has dynamic resource management that is somewhat based on the RAM you have in your system. I am currently experimenting with different input formats, it looks like this has an impact on RAM usage.

> there was no sign of GIF even though I went through the process of naming it and saving under " Videos " before it hung

That is to be expected, the file gets placed there when ImageMagick finishes. As you did not let it finish there is no file.

I am closing this. Not because it is not relevant but because there are already multiple issues all having the same root cause (high RAM usage).

**Closed by phw** 2017-04-21 08:18 UTC
Labels: duplicate
