### ISSUE TITLE
Recording error if gifski is used

### ISSUE THREAD

**Issue by zensubz** [phw/peek#240] opened 2017-11-29 15:54 UTC
Hi,
Thanks for this excellent app. I have tried both the release (v1.2.0) and the git-master branch. The app works perfectly, but then, it doesn't allow me to save the files if I use gifski. It just throws out an error (screenshot attached). How to overcome this issue, if I want to have high-quality gif file (as gifski seems to be of help that way).

![peek-gifski-error](https://user-images.githubusercontent.com/5127872/33384232-7788489e-d54b-11e7-98e9-4a94e7cd5a56.png)

**Comment by phw** [comment] 2017-12-01 08:38
Unfortunately this does not tell us much. I have to see if I can improve the error output here, I would have at least expected the gifski command to fail, in which case its error output should be visible here.

Can you try whether gifski works for you to convert a video from command line? Follow the instructions on https://github.com/ImageOptim/gifski to convert a video to PNG files using ffmpeg and then convert those files to a GIF with gifski. Basically this is:

    ffmpeg -i video.webm frame%04d.png
    gifski -o anim.gif frame*.png

**Comment by zensubz** [comment] 2017-12-01 14:24
Hi,

Thanks for your kind response. Yes, the issue seems to be with gifski. I prepared a small video with peek in webm format and did the exercise you have mentioned. The output (when gifski was called-in) is:

gifski -o testanim.gif frame*.png
Frame 2 / 178  _............................................................................... 18m Segmentation fault

I had actually downloaded gifski (v0.6.1, release binary from its website), and it indeed gives information when invoked with 'gifski --help' via command-line. But it fails, at least in my case, to do the conversion job. 

Other than this small issue involving gifski, there is as such no problem working with your great software. I am not sure if I have to file any bug-report to gifski - compiling it from source seems to be a bit tedious as I don't have rust/cargo in my system.

**Comment by phw** [comment] 2017-12-03 16:50
I fear the only workaround is to compile gifski yourself. I also had issues on some systems with gifski being compiled with openmp support, the workaround then is to compile it without this. Also https://github.com/ImageOptim/gifski/issues/9 might be releated.

I am going to close this here, as this should be solved in gifski.

**Closed by phw** 2017-12-03 16:50 UTC
Labels: upstream

**Comment by ernstki** [comment] 2018-01-10 01:10
I can confirm that compiling gifski from source (using `rustup-init` from [here](https://github.com/rust-lang-nursery/rustup.rs/#other-installation-methods)) and no extra options beyond what're mentioned in ImageOptim/gifski#9 fixed this problem for me on elementaryOS Loki (0.4, which derives from Ubuntu 16.something).

A summary of the steps necessary:

```bash
# if you're bold and brave
curl https://sh.rustup.rs -sSf | sh
# or else https://github.com/rust-lang-nursery/rustup.rs/#other-installation-methods

# we need to have ~/.cargo/bin in our path
echo 'source $HOME/.cargo/env' >> .bashrc
source $HOME/.cargo/env

cd /place/where/you/do/dev/stuff
git clone https://github.com/ImageOptim/gifski.git
cd gifski
cargo run --release
cargo install
```

Finally, either run `peek` from that same shell or log out and back in again, since your login shell won't have `~/.cargo/bin` in your path until you do that. Peek won't show the "Use gifski" option unless it finds it in your `$PATH`.

**Comment by Moini** [comment] 2018-03-15 19:39
Works with gifski 0.8.2 from https://gif.ski/
